// Copyright 2019-present Facebook
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// Code generated by entc, DO NOT EDIT.

package ent

import (
	"net/http"
	"strconv"

	"entgo.io/ent/entc/integration/ent"
	"github.com/gofiber/fiber/v2"
	"github.com/masseelch/elk/internal/integration/pets/ent/badge"
	"github.com/valyala/fasthttp/fasthttpadaptor"
	"go.uber.org/zap"
)

// @Summary Read a Badge
// @Description Read a Badge
// @ID Read a Badge
// @Tags [Badge]
// @Accept  json
// @Produce  json
// @Param id path int true "Badge ID"
// @Success 200 {object} ent.Badge
// @Failure 400 {object} main.HTTPError
// @Failure 404 {object} main.HTTPError
// @Failure 500 {object} main.HTTPError
// @Router /badge/{id} [get]
// Read fetches the ent.Badge identified by a given url-parameter from the
// database and renders it to the client.
func (h *BadgeHandler) Read(c *fiber.Ctx) error {
	l := h.log.With(zap.String("method", "Read"))
	// ID is URL parameter.
	id, err := strconv.Atoi(c.Params("id"))
	if err != nil {
		l.Error("error getting id from url parameter", zap.String("id", c.Params("id")), zap.Error(err))
		return c.Status(400).SendString("id must be an integer greater zero")
	}
	var r http.Request
	fasthttpadaptor.ConvertRequest(c.Context(), &r, true)
	// Create the query to fetch the Badge
	q := h.client.Badge.Query().Where(badge.ID(id))
	e, err := q.Only(r.Context())
	if err != nil {
		switch {
		case ent.IsNotFound(err):
			msg := stripEntError(err)
			l.Info(msg, zap.Error(err), zap.Int("id", id))
			c.Status(404).SendString(msg)
		case ent.IsNotSingular(err):
			msg := stripEntError(err)
			l.Error(msg, zap.Error(err), zap.Int("id", id))
			c.Status(400).SendString(msg)
		default:
			l.Error("could not read badge", zap.Error(err), zap.Int("id", id))
			c.Status(fiber.StatusInternalServerError).SendString("Serve Error")
		}
		return nil
	}
	l.Info("badge rendered", zap.Int("id", id))
	return c.JSON(NewBadge2492344257View(e))
}

// Payload of a ent.Badge create request.
type BadgeCreateRequest struct {
	Color    *badge.Color    `json:"color"`
	Material *badge.Material `json:"material"`
	Wearer   *int            `json:"wearer"`
}

// @Summary Create a Badge
// @Description create a Badge
// @ID Create new Badge
// @Tags [Badge]
// @Accept  json
// @Produce  json
// @Success 200 {object} ent.Badge
// @Failure 400 {object} main.HTTPError
// @Failure 404 {object} main.HTTPError
// @Failure 500 {object} main.HTTPError
// @Router /badge [post]
// Create creates a new ent.Badge and stores it in the database.
func (h BadgeHandler) Create(c *fiber.Ctx) error {
	l := h.log.With(zap.String("method", "Create"))
	// Get the post data.
	d := new(BadgeCreateRequest)
	var r http.Request
	fasthttpadaptor.ConvertRequest(c.Context(), &r, true)

	if err := c.BodyParser(d); err != nil {
		l.Error("error decoding json", zap.Error(err))
		return c.Status(400).SendString("invalid json string")
	}
	// Save the data.
	b := h.client.Badge.Create()
	if d.Color != nil {
		b.SetColor(*d.Color)
	}
	if d.Material != nil {
		b.SetMaterial(*d.Material)
	}
	if d.Wearer != nil {
		b.SetWearerID(*d.Wearer)
	}
	e, err := b.Save(r.Context())
	if err != nil {
		switch {
		default:
			l.Error("could not create badge", zap.Error(err))
			c.Status(fiber.StatusInternalServerError).SendString("Serve Error")
		}
		return nil
	}
	// Reload entry.
	q := h.client.Badge.Query().Where(badge.ID(e.ID))
	e, err = q.Only(r.Context())
	if err != nil {
		switch {
		case ent.IsNotFound(err):
			msg := stripEntError(err)
			l.Info(msg, zap.Error(err), zap.Int("id", e.ID))
			c.Status(404).SendString(msg)
		case ent.IsNotSingular(err):
			msg := stripEntError(err)
			l.Error(msg, zap.Error(err), zap.Int("id", e.ID))
			c.Status(400).SendString(msg)
		default:
			l.Error("could not read badge", zap.Error(err), zap.Int("id", e.ID))
			c.Status(fiber.StatusInternalServerError).SendString("Serve Error")
		}
		return nil
	}
	l.Info("badge rendered", zap.Int("id", e.ID))
	return c.JSON(NewBadge2492344257View(e))
}

// @Summary Delete a Badge
// @Description Delete a Badge
// @ID Delete a Badge
// @Tags [Badge]
// @Accept  json
// @Produce  json
// @Param id path int true "Badge ID"
// @Success 200 {object} ent.Badge
// @Failure 400 {object} main.HTTPError
// @Failure 404 {object} main.HTTPError
// @Failure 500 {object} main.HTTPError
// @Router /badge/{id} [delete]
// Delete removes a ent.Badge from the database.
func (h BadgeHandler) Delete(c *fiber.Ctx) error {
	l := h.log.With(zap.String("method", "Delete"))
	// ID is URL parameter.
	id, err := strconv.Atoi(c.Params("id"))
	if err != nil {
		l.Error("error getting id from url parameter", zap.String("id", c.Params("id")), zap.Error(err))
		return c.Status(400).SendString("id must be an integer greater zero")
	}
	var r http.Request
	fasthttpadaptor.ConvertRequest(c.Context(), &r, true)
	err = h.client.Badge.DeleteOneID(id).Exec(r.Context())
	if err != nil {
		switch {
		case ent.IsNotFound(err):
			msg := stripEntError(err)
			l.Info(msg, zap.Error(err), zap.Int("id", id))
			c.Status(404).SendString(msg)
		default:
			l.Error("could-not-delete-badge", zap.Error(err), zap.Int("id", id))
			c.Status(fiber.StatusInternalServerError).SendString("Serve Error")
		}
		return nil
	}
	l.Info("badge deleted", zap.Int("id", id))
	return c.SendString("Delete successfully")
}

// @Summary Fetches Badge
// @Description Fetches Badge
// @ID Fetches Badge
// @Tags [Badge]
// @Accept  json
// @Produce  json
// @Success 200 {array} ent.Badge
// @Failure 400 {object} main.HTTPError
// @Failure 404 {object} main.HTTPError
// @Failure 500 {object} main.HTTPError
// @Router /badge [get]
// Read fetches the ent.Badge identified by a given url-parameter from the
// database and returns it to the client.
func (h *BadgeHandler) List(c *fiber.Ctx) error {
	l := h.log.With(zap.String("method", "List"))
	q := h.client.Badge.Query()
	var r http.Request
	fasthttpadaptor.ConvertRequest(c.Context(), &r, true)
	var err error
	page := 1
	if d := c.Query("page"); d != "" {
		page, err = strconv.Atoi(d)
		if err != nil {
			l.Info("error parsing query parameter 'page'", zap.String("page", d), zap.Error(err))
			return c.Status(400).SendString("page must be an integer greater zero")
		}
	}
	itemsPerPage := 30
	if d := c.Query("itemsPerPage"); d != "" {
		itemsPerPage, err = strconv.Atoi(d)
		if err != nil {
			l.Info("error parsing query parameter 'itemsPerPage'", zap.String("itemsPerPage", d), zap.Error(err))
			return c.Status(400).SendString("itemsPerPage must be an integer greater zero")
		}
	}
	es, err := q.Limit(itemsPerPage).Offset((page - 1) * itemsPerPage).All(r.Context())
	if err != nil {
		l.Error("error fetching badges from db", zap.Error(err))
		return c.Status(fiber.StatusInternalServerError).SendString("Serve Error")
	}
	l.Info("badges rendered", zap.Int("amount", len(es)))
	return c.JSON(NewBadge2492344257Views(es))
}

// Payload of a ent.Badge update request.
type BadgeUpdateRequest struct {
	Color    *badge.Color    `json:"color"`
	Material *badge.Material `json:"material"`
	Wearer   *int            `json:"wearer"`
}

// @Summary Update a Badge
// @Description Update a Badge
// @ID Update a Badge
// @Tags [Badge]
// @Accept  json
// @Produce  json
// @Param id path int true "Badge ID"
// @Success 200 {object} ent.Badge
// @Failure 400 {object} main.HTTPError
// @Failure 404 {object} main.HTTPError
// @Failure 500 {object} main.HTTPError
// @Router /badge/{id} [patch]
// Update updates a given ent.Badge and saves the changes to the database.
func (h BadgeHandler) Update(c *fiber.Ctx) error {
	l := h.log.With(zap.String("method", "Update"))
	// ID is URL parameter.
	id, err := strconv.Atoi(c.Params("id"))
	if err != nil {
		l.Error("error getting id from url parameter", zap.String("id", c.Params("id")), zap.Error(err))
		return c.Status(400).SendString("id must be an integer greater zero")
	}
	// Get the post data.
	d := new(BadgeUpdateRequest)
	var r http.Request
	fasthttpadaptor.ConvertRequest(c.Context(), &r, true)

	if err := c.BodyParser(d); err != nil {
		l.Error("error decoding json", zap.Error(err))
		return c.Status(400).SendString("invalid json string")
	}
	// Save the data.
	b := h.client.Badge.UpdateOneID(id)
	if d.Color != nil {
		b.SetColor(*d.Color)
	}
	if d.Material != nil {
		b.SetMaterial(*d.Material)
	}
	if d.Wearer != nil {
		b.SetWearerID(*d.Wearer)

	}
	// Store in database.
	e, err := b.Save(r.Context())
	if err != nil {
		switch {
		case ent.IsNotFound(err):
			msg := stripEntError(err)
			l.Info(msg, zap.Error(err), zap.Int("id", id))
			c.Status(404).SendString(msg)
		case ent.IsNotSingular(err):
			msg := stripEntError(err)
			l.Error(msg, zap.Error(err), zap.Int("id", id))
			c.Status(400).SendString(msg)
		default:
			l.Error("could-not-update-badge", zap.Error(err), zap.Int("id", id))
			c.Status(fiber.StatusInternalServerError).SendString("Serve Error")
		}
		return nil
	}
	// Reload entry.
	q := h.client.Badge.Query().Where(badge.ID(e.ID))
	e, err = q.Only(r.Context())
	if err != nil {
		switch {
		case ent.IsNotFound(err):
			msg := stripEntError(err)
			l.Info(msg, zap.Error(err), zap.Int("id", id))
			c.Status(404).SendString(msg)
		case ent.IsNotSingular(err):
			msg := stripEntError(err)
			l.Error(msg, zap.Error(err), zap.Int("id", id))
			c.Status(400).SendString(msg)
		default:
			l.Error("could-not-read-badge", zap.Error(err), zap.Int("id", id))
			c.Status(fiber.StatusInternalServerError).SendString("Serve Error")
		}
		return nil
	}
	l.Info("badge rendered", zap.Int("id", e.ID))
	return c.JSON(NewBadge2492344257View(e))
}

// @Summary Get Badge with Wearer
// @Description Get Badge with Wearer
// @ID Get Badge with Wearer
// @Tags [Badge]
// @Accept  json
// @Produce  json
// @Param id path int true "Badge ID"
// @Success 200 {object} ent.Badge
// @Failure 400 {object} main.HTTPError
// @Failure 404 {object} main.HTTPError
// @Failure 500 {object} main.HTTPError
// @Router /badge/{id}/wearer [get]
// Wearer fetches the ent.wearer attached to the ent.Badge
// identified by a given url-parameter from the database and renders it to the client.
func (h BadgeHandler) Wearer(c *fiber.Ctx) error {
	l := h.log.With(zap.String("method", "Wearer"))
	// ID is URL parameter.
	id, err := strconv.Atoi(c.Params("id"))
	if err != nil {
		l.Error("error getting id from url parameter", zap.String("id", c.Params("id")), zap.Error(err))
		return c.Status(400).SendString("id must be an integer greater zero")
	}
	var r http.Request
	fasthttpadaptor.ConvertRequest(c.Context(), &r, true)
	// Create the query to fetch the wearer attached to this badge
	q := h.client.Badge.Query().Where(badge.ID(id)).QueryWearer()
	// Eager load edges that are required on read operation.
	q.WithBadge().WithProtege(func(q *ent.PetQuery) {
		q.WithBadge().WithSpouse(func(q *ent.PetQuery) {
			q.WithBadge().WithToys().WithParent(func(q *ent.PetQuery) {
				q.WithBadge().WithToys().WithParent(func(q *ent.PetQuery) {
					q.WithBadge().WithToys().WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
						q.WithBadge().WithToys().WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						})
					})
				}).WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
					q.WithBadge().WithToys().WithParent(func(q *ent.PetQuery) {
						q.WithBadge().WithToys().WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						})
					}).WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
						q.WithBadge().WithToys().WithParent(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						}).WithPlayGroups()
					})
				})
			}).WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
				q.WithBadge().WithToys().WithParent(func(q *ent.PetQuery) {
					q.WithBadge().WithToys().WithParent(func(q *ent.PetQuery) {
						q.WithBadge().WithToys().WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						})
					}).WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
						q.WithBadge().WithToys().WithParent(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						}).WithPlayGroups()
					})
				}).WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
					q.WithBadge().WithToys().WithParent(func(q *ent.PetQuery) {
						q.WithBadge().WithToys().WithParent(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						}).WithPlayGroups()
					}).WithPlayGroups()
				})
			})
		}).WithToys().WithParent(func(q *ent.PetQuery) {
			q.WithBadge().WithSpouse(func(q *ent.PetQuery) {
				q.WithBadge().WithToys().WithParent(func(q *ent.PetQuery) {
					q.WithBadge().WithToys().WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
						q.WithBadge().WithToys().WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						})
					})
				}).WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
					q.WithBadge().WithToys().WithParent(func(q *ent.PetQuery) {
						q.WithBadge().WithToys().WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						})
					}).WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
						q.WithBadge().WithToys().WithParent(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						}).WithPlayGroups()
					})
				})
			}).WithToys().WithParent(func(q *ent.PetQuery) {
				q.WithBadge().WithSpouse(func(q *ent.PetQuery) {
					q.WithBadge().WithToys().WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
						q.WithBadge().WithToys().WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						})
					})
				}).WithToys().WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
					q.WithBadge().WithSpouse(func(q *ent.PetQuery) {
						q.WithBadge().WithToys().WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						})
					}).WithToys().WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
						q.WithBadge().WithSpouse(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						}).WithToys().WithPlayGroups()
					})
				})
			}).WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
				q.WithBadge().WithSpouse(func(q *ent.PetQuery) {
					q.WithBadge().WithToys().WithParent(func(q *ent.PetQuery) {
						q.WithBadge().WithToys().WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						})
					}).WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
						q.WithBadge().WithToys().WithParent(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						}).WithPlayGroups()
					})
				}).WithToys().WithParent(func(q *ent.PetQuery) {
					q.WithBadge().WithSpouse(func(q *ent.PetQuery) {
						q.WithBadge().WithToys().WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						})
					}).WithToys().WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
						q.WithBadge().WithSpouse(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						}).WithToys().WithPlayGroups()
					})
				}).WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
					q.WithBadge().WithSpouse(func(q *ent.PetQuery) {
						q.WithBadge().WithToys().WithParent(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						}).WithPlayGroups()
					}).WithToys().WithParent(func(q *ent.PetQuery) {
						q.WithBadge().WithSpouse(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						}).WithToys().WithPlayGroups()
					}).WithPlayGroups()
				})
			})
		}).WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
			q.WithBadge().WithSpouse(func(q *ent.PetQuery) {
				q.WithBadge().WithToys().WithParent(func(q *ent.PetQuery) {
					q.WithBadge().WithToys().WithParent(func(q *ent.PetQuery) {
						q.WithBadge().WithToys().WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						})
					}).WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
						q.WithBadge().WithToys().WithParent(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						}).WithPlayGroups()
					})
				}).WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
					q.WithBadge().WithToys().WithParent(func(q *ent.PetQuery) {
						q.WithBadge().WithToys().WithParent(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						}).WithPlayGroups()
					}).WithPlayGroups()
				})
			}).WithToys().WithParent(func(q *ent.PetQuery) {
				q.WithBadge().WithSpouse(func(q *ent.PetQuery) {
					q.WithBadge().WithToys().WithParent(func(q *ent.PetQuery) {
						q.WithBadge().WithToys().WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						})
					}).WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
						q.WithBadge().WithToys().WithParent(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						}).WithPlayGroups()
					})
				}).WithToys().WithParent(func(q *ent.PetQuery) {
					q.WithBadge().WithSpouse(func(q *ent.PetQuery) {
						q.WithBadge().WithToys().WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						})
					}).WithToys().WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
						q.WithBadge().WithSpouse(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						}).WithToys().WithPlayGroups()
					})
				}).WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
					q.WithBadge().WithSpouse(func(q *ent.PetQuery) {
						q.WithBadge().WithToys().WithParent(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						}).WithPlayGroups()
					}).WithToys().WithParent(func(q *ent.PetQuery) {
						q.WithBadge().WithSpouse(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						}).WithToys().WithPlayGroups()
					}).WithPlayGroups()
				})
			}).WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
				q.WithBadge().WithSpouse(func(q *ent.PetQuery) {
					q.WithBadge().WithToys().WithParent(func(q *ent.PetQuery) {
						q.WithBadge().WithToys().WithParent(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						}).WithPlayGroups()
					}).WithPlayGroups()
				}).WithToys().WithParent(func(q *ent.PetQuery) {
					q.WithBadge().WithSpouse(func(q *ent.PetQuery) {
						q.WithBadge().WithToys().WithParent(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						}).WithPlayGroups()
					}).WithToys().WithParent(func(q *ent.PetQuery) {
						q.WithBadge().WithSpouse(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						}).WithToys().WithPlayGroups()
					}).WithPlayGroups()
				}).WithPlayGroups()
			})
		})
	}).WithSpouse(func(q *ent.PetQuery) {
		q.WithBadge().WithProtege(func(q *ent.PetQuery) {
			q.WithBadge().WithToys().WithParent(func(q *ent.PetQuery) {
				q.WithBadge().WithToys().WithParent(func(q *ent.PetQuery) {
					q.WithBadge().WithToys().WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
						q.WithBadge().WithToys().WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						})
					})
				}).WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
					q.WithBadge().WithToys().WithParent(func(q *ent.PetQuery) {
						q.WithBadge().WithToys().WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						})
					}).WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
						q.WithBadge().WithToys().WithParent(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						}).WithPlayGroups()
					})
				})
			}).WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
				q.WithBadge().WithToys().WithParent(func(q *ent.PetQuery) {
					q.WithBadge().WithToys().WithParent(func(q *ent.PetQuery) {
						q.WithBadge().WithToys().WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						})
					}).WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
						q.WithBadge().WithToys().WithParent(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						}).WithPlayGroups()
					})
				}).WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
					q.WithBadge().WithToys().WithParent(func(q *ent.PetQuery) {
						q.WithBadge().WithToys().WithParent(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						}).WithPlayGroups()
					}).WithPlayGroups()
				})
			})
		}).WithToys().WithParent(func(q *ent.PetQuery) {
			q.WithBadge().WithProtege(func(q *ent.PetQuery) {
				q.WithBadge().WithToys().WithParent(func(q *ent.PetQuery) {
					q.WithBadge().WithToys().WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
						q.WithBadge().WithToys().WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						})
					})
				}).WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
					q.WithBadge().WithToys().WithParent(func(q *ent.PetQuery) {
						q.WithBadge().WithToys().WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						})
					}).WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
						q.WithBadge().WithToys().WithParent(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						}).WithPlayGroups()
					})
				})
			}).WithToys().WithParent(func(q *ent.PetQuery) {
				q.WithBadge().WithProtege(func(q *ent.PetQuery) {
					q.WithBadge().WithToys().WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
						q.WithBadge().WithToys().WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						})
					})
				}).WithToys().WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
					q.WithBadge().WithProtege(func(q *ent.PetQuery) {
						q.WithBadge().WithToys().WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						})
					}).WithToys().WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
						q.WithBadge().WithProtege(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						}).WithToys().WithPlayGroups()
					})
				})
			}).WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
				q.WithBadge().WithProtege(func(q *ent.PetQuery) {
					q.WithBadge().WithToys().WithParent(func(q *ent.PetQuery) {
						q.WithBadge().WithToys().WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						})
					}).WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
						q.WithBadge().WithToys().WithParent(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						}).WithPlayGroups()
					})
				}).WithToys().WithParent(func(q *ent.PetQuery) {
					q.WithBadge().WithProtege(func(q *ent.PetQuery) {
						q.WithBadge().WithToys().WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						})
					}).WithToys().WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
						q.WithBadge().WithProtege(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						}).WithToys().WithPlayGroups()
					})
				}).WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
					q.WithBadge().WithProtege(func(q *ent.PetQuery) {
						q.WithBadge().WithToys().WithParent(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						}).WithPlayGroups()
					}).WithToys().WithParent(func(q *ent.PetQuery) {
						q.WithBadge().WithProtege(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						}).WithToys().WithPlayGroups()
					}).WithPlayGroups()
				})
			})
		}).WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
			q.WithBadge().WithProtege(func(q *ent.PetQuery) {
				q.WithBadge().WithToys().WithParent(func(q *ent.PetQuery) {
					q.WithBadge().WithToys().WithParent(func(q *ent.PetQuery) {
						q.WithBadge().WithToys().WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						})
					}).WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
						q.WithBadge().WithToys().WithParent(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						}).WithPlayGroups()
					})
				}).WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
					q.WithBadge().WithToys().WithParent(func(q *ent.PetQuery) {
						q.WithBadge().WithToys().WithParent(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						}).WithPlayGroups()
					}).WithPlayGroups()
				})
			}).WithToys().WithParent(func(q *ent.PetQuery) {
				q.WithBadge().WithProtege(func(q *ent.PetQuery) {
					q.WithBadge().WithToys().WithParent(func(q *ent.PetQuery) {
						q.WithBadge().WithToys().WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						})
					}).WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
						q.WithBadge().WithToys().WithParent(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						}).WithPlayGroups()
					})
				}).WithToys().WithParent(func(q *ent.PetQuery) {
					q.WithBadge().WithProtege(func(q *ent.PetQuery) {
						q.WithBadge().WithToys().WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						})
					}).WithToys().WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
						q.WithBadge().WithProtege(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						}).WithToys().WithPlayGroups()
					})
				}).WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
					q.WithBadge().WithProtege(func(q *ent.PetQuery) {
						q.WithBadge().WithToys().WithParent(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						}).WithPlayGroups()
					}).WithToys().WithParent(func(q *ent.PetQuery) {
						q.WithBadge().WithProtege(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						}).WithToys().WithPlayGroups()
					}).WithPlayGroups()
				})
			}).WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
				q.WithBadge().WithProtege(func(q *ent.PetQuery) {
					q.WithBadge().WithToys().WithParent(func(q *ent.PetQuery) {
						q.WithBadge().WithToys().WithParent(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						}).WithPlayGroups()
					}).WithPlayGroups()
				}).WithToys().WithParent(func(q *ent.PetQuery) {
					q.WithBadge().WithProtege(func(q *ent.PetQuery) {
						q.WithBadge().WithToys().WithParent(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						}).WithPlayGroups()
					}).WithToys().WithParent(func(q *ent.PetQuery) {
						q.WithBadge().WithProtege(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						}).WithToys().WithPlayGroups()
					}).WithPlayGroups()
				}).WithPlayGroups()
			})
		})
	}).WithToys().WithParent(func(q *ent.PetQuery) {
		q.WithBadge().WithProtege(func(q *ent.PetQuery) {
			q.WithBadge().WithSpouse(func(q *ent.PetQuery) {
				q.WithBadge().WithToys().WithParent(func(q *ent.PetQuery) {
					q.WithBadge().WithToys().WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
						q.WithBadge().WithToys().WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						})
					})
				}).WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
					q.WithBadge().WithToys().WithParent(func(q *ent.PetQuery) {
						q.WithBadge().WithToys().WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						})
					}).WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
						q.WithBadge().WithToys().WithParent(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						}).WithPlayGroups()
					})
				})
			}).WithToys().WithParent(func(q *ent.PetQuery) {
				q.WithBadge().WithSpouse(func(q *ent.PetQuery) {
					q.WithBadge().WithToys().WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
						q.WithBadge().WithToys().WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						})
					})
				}).WithToys().WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
					q.WithBadge().WithSpouse(func(q *ent.PetQuery) {
						q.WithBadge().WithToys().WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						})
					}).WithToys().WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
						q.WithBadge().WithSpouse(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						}).WithToys().WithPlayGroups()
					})
				})
			}).WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
				q.WithBadge().WithSpouse(func(q *ent.PetQuery) {
					q.WithBadge().WithToys().WithParent(func(q *ent.PetQuery) {
						q.WithBadge().WithToys().WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						})
					}).WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
						q.WithBadge().WithToys().WithParent(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						}).WithPlayGroups()
					})
				}).WithToys().WithParent(func(q *ent.PetQuery) {
					q.WithBadge().WithSpouse(func(q *ent.PetQuery) {
						q.WithBadge().WithToys().WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						})
					}).WithToys().WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
						q.WithBadge().WithSpouse(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						}).WithToys().WithPlayGroups()
					})
				}).WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
					q.WithBadge().WithSpouse(func(q *ent.PetQuery) {
						q.WithBadge().WithToys().WithParent(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						}).WithPlayGroups()
					}).WithToys().WithParent(func(q *ent.PetQuery) {
						q.WithBadge().WithSpouse(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						}).WithToys().WithPlayGroups()
					}).WithPlayGroups()
				})
			})
		}).WithSpouse(func(q *ent.PetQuery) {
			q.WithBadge().WithProtege(func(q *ent.PetQuery) {
				q.WithBadge().WithToys().WithParent(func(q *ent.PetQuery) {
					q.WithBadge().WithToys().WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
						q.WithBadge().WithToys().WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						})
					})
				}).WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
					q.WithBadge().WithToys().WithParent(func(q *ent.PetQuery) {
						q.WithBadge().WithToys().WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						})
					}).WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
						q.WithBadge().WithToys().WithParent(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						}).WithPlayGroups()
					})
				})
			}).WithToys().WithParent(func(q *ent.PetQuery) {
				q.WithBadge().WithProtege(func(q *ent.PetQuery) {
					q.WithBadge().WithToys().WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
						q.WithBadge().WithToys().WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						})
					})
				}).WithToys().WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
					q.WithBadge().WithProtege(func(q *ent.PetQuery) {
						q.WithBadge().WithToys().WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						})
					}).WithToys().WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
						q.WithBadge().WithProtege(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						}).WithToys().WithPlayGroups()
					})
				})
			}).WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
				q.WithBadge().WithProtege(func(q *ent.PetQuery) {
					q.WithBadge().WithToys().WithParent(func(q *ent.PetQuery) {
						q.WithBadge().WithToys().WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						})
					}).WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
						q.WithBadge().WithToys().WithParent(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						}).WithPlayGroups()
					})
				}).WithToys().WithParent(func(q *ent.PetQuery) {
					q.WithBadge().WithProtege(func(q *ent.PetQuery) {
						q.WithBadge().WithToys().WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						})
					}).WithToys().WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
						q.WithBadge().WithProtege(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						}).WithToys().WithPlayGroups()
					})
				}).WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
					q.WithBadge().WithProtege(func(q *ent.PetQuery) {
						q.WithBadge().WithToys().WithParent(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						}).WithPlayGroups()
					}).WithToys().WithParent(func(q *ent.PetQuery) {
						q.WithBadge().WithProtege(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						}).WithToys().WithPlayGroups()
					}).WithPlayGroups()
				})
			})
		}).WithToys().WithParent(func(q *ent.PetQuery) {
			q.WithBadge().WithProtege(func(q *ent.PetQuery) {
				q.WithBadge().WithSpouse(func(q *ent.PetQuery) {
					q.WithBadge().WithToys().WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
						q.WithBadge().WithToys().WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						})
					})
				}).WithToys().WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
					q.WithBadge().WithSpouse(func(q *ent.PetQuery) {
						q.WithBadge().WithToys().WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						})
					}).WithToys().WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
						q.WithBadge().WithSpouse(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						}).WithToys().WithPlayGroups()
					})
				})
			}).WithSpouse(func(q *ent.PetQuery) {
				q.WithBadge().WithProtege(func(q *ent.PetQuery) {
					q.WithBadge().WithToys().WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
						q.WithBadge().WithToys().WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						})
					})
				}).WithToys().WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
					q.WithBadge().WithProtege(func(q *ent.PetQuery) {
						q.WithBadge().WithToys().WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						})
					}).WithToys().WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
						q.WithBadge().WithProtege(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						}).WithToys().WithPlayGroups()
					})
				})
			}).WithToys().WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
				q.WithBadge().WithProtege(func(q *ent.PetQuery) {
					q.WithBadge().WithSpouse(func(q *ent.PetQuery) {
						q.WithBadge().WithToys().WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						})
					}).WithToys().WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
						q.WithBadge().WithSpouse(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						}).WithToys().WithPlayGroups()
					})
				}).WithSpouse(func(q *ent.PetQuery) {
					q.WithBadge().WithProtege(func(q *ent.PetQuery) {
						q.WithBadge().WithToys().WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						})
					}).WithToys().WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
						q.WithBadge().WithProtege(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						}).WithToys().WithPlayGroups()
					})
				}).WithToys().WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
					q.WithBadge().WithProtege(func(q *ent.PetQuery) {
						q.WithBadge().WithSpouse(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						}).WithToys().WithPlayGroups()
					}).WithSpouse(func(q *ent.PetQuery) {
						q.WithBadge().WithProtege(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						}).WithToys().WithPlayGroups()
					}).WithToys().WithPlayGroups()
				})
			})
		}).WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
			q.WithBadge().WithProtege(func(q *ent.PetQuery) {
				q.WithBadge().WithSpouse(func(q *ent.PetQuery) {
					q.WithBadge().WithToys().WithParent(func(q *ent.PetQuery) {
						q.WithBadge().WithToys().WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						})
					}).WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
						q.WithBadge().WithToys().WithParent(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						}).WithPlayGroups()
					})
				}).WithToys().WithParent(func(q *ent.PetQuery) {
					q.WithBadge().WithSpouse(func(q *ent.PetQuery) {
						q.WithBadge().WithToys().WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						})
					}).WithToys().WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
						q.WithBadge().WithSpouse(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						}).WithToys().WithPlayGroups()
					})
				}).WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
					q.WithBadge().WithSpouse(func(q *ent.PetQuery) {
						q.WithBadge().WithToys().WithParent(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						}).WithPlayGroups()
					}).WithToys().WithParent(func(q *ent.PetQuery) {
						q.WithBadge().WithSpouse(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						}).WithToys().WithPlayGroups()
					}).WithPlayGroups()
				})
			}).WithSpouse(func(q *ent.PetQuery) {
				q.WithBadge().WithProtege(func(q *ent.PetQuery) {
					q.WithBadge().WithToys().WithParent(func(q *ent.PetQuery) {
						q.WithBadge().WithToys().WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						})
					}).WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
						q.WithBadge().WithToys().WithParent(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						}).WithPlayGroups()
					})
				}).WithToys().WithParent(func(q *ent.PetQuery) {
					q.WithBadge().WithProtege(func(q *ent.PetQuery) {
						q.WithBadge().WithToys().WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						})
					}).WithToys().WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
						q.WithBadge().WithProtege(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						}).WithToys().WithPlayGroups()
					})
				}).WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
					q.WithBadge().WithProtege(func(q *ent.PetQuery) {
						q.WithBadge().WithToys().WithParent(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						}).WithPlayGroups()
					}).WithToys().WithParent(func(q *ent.PetQuery) {
						q.WithBadge().WithProtege(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						}).WithToys().WithPlayGroups()
					}).WithPlayGroups()
				})
			}).WithToys().WithParent(func(q *ent.PetQuery) {
				q.WithBadge().WithProtege(func(q *ent.PetQuery) {
					q.WithBadge().WithSpouse(func(q *ent.PetQuery) {
						q.WithBadge().WithToys().WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						})
					}).WithToys().WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
						q.WithBadge().WithSpouse(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						}).WithToys().WithPlayGroups()
					})
				}).WithSpouse(func(q *ent.PetQuery) {
					q.WithBadge().WithProtege(func(q *ent.PetQuery) {
						q.WithBadge().WithToys().WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						})
					}).WithToys().WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
						q.WithBadge().WithProtege(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						}).WithToys().WithPlayGroups()
					})
				}).WithToys().WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
					q.WithBadge().WithProtege(func(q *ent.PetQuery) {
						q.WithBadge().WithSpouse(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						}).WithToys().WithPlayGroups()
					}).WithSpouse(func(q *ent.PetQuery) {
						q.WithBadge().WithProtege(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						}).WithToys().WithPlayGroups()
					}).WithToys().WithPlayGroups()
				})
			}).WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
				q.WithBadge().WithProtege(func(q *ent.PetQuery) {
					q.WithBadge().WithSpouse(func(q *ent.PetQuery) {
						q.WithBadge().WithToys().WithParent(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						}).WithPlayGroups()
					}).WithToys().WithParent(func(q *ent.PetQuery) {
						q.WithBadge().WithSpouse(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						}).WithToys().WithPlayGroups()
					}).WithPlayGroups()
				}).WithSpouse(func(q *ent.PetQuery) {
					q.WithBadge().WithProtege(func(q *ent.PetQuery) {
						q.WithBadge().WithToys().WithParent(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						}).WithPlayGroups()
					}).WithToys().WithParent(func(q *ent.PetQuery) {
						q.WithBadge().WithProtege(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						}).WithToys().WithPlayGroups()
					}).WithPlayGroups()
				}).WithToys().WithParent(func(q *ent.PetQuery) {
					q.WithBadge().WithProtege(func(q *ent.PetQuery) {
						q.WithBadge().WithSpouse(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						}).WithToys().WithPlayGroups()
					}).WithSpouse(func(q *ent.PetQuery) {
						q.WithBadge().WithProtege(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						}).WithToys().WithPlayGroups()
					}).WithToys().WithPlayGroups()
				}).WithPlayGroups()
			})
		})
	}).WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
		q.WithBadge().WithProtege(func(q *ent.PetQuery) {
			q.WithBadge().WithSpouse(func(q *ent.PetQuery) {
				q.WithBadge().WithToys().WithParent(func(q *ent.PetQuery) {
					q.WithBadge().WithToys().WithParent(func(q *ent.PetQuery) {
						q.WithBadge().WithToys().WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						})
					}).WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
						q.WithBadge().WithToys().WithParent(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						}).WithPlayGroups()
					})
				}).WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
					q.WithBadge().WithToys().WithParent(func(q *ent.PetQuery) {
						q.WithBadge().WithToys().WithParent(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						}).WithPlayGroups()
					}).WithPlayGroups()
				})
			}).WithToys().WithParent(func(q *ent.PetQuery) {
				q.WithBadge().WithSpouse(func(q *ent.PetQuery) {
					q.WithBadge().WithToys().WithParent(func(q *ent.PetQuery) {
						q.WithBadge().WithToys().WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						})
					}).WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
						q.WithBadge().WithToys().WithParent(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						}).WithPlayGroups()
					})
				}).WithToys().WithParent(func(q *ent.PetQuery) {
					q.WithBadge().WithSpouse(func(q *ent.PetQuery) {
						q.WithBadge().WithToys().WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						})
					}).WithToys().WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
						q.WithBadge().WithSpouse(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						}).WithToys().WithPlayGroups()
					})
				}).WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
					q.WithBadge().WithSpouse(func(q *ent.PetQuery) {
						q.WithBadge().WithToys().WithParent(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						}).WithPlayGroups()
					}).WithToys().WithParent(func(q *ent.PetQuery) {
						q.WithBadge().WithSpouse(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						}).WithToys().WithPlayGroups()
					}).WithPlayGroups()
				})
			}).WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
				q.WithBadge().WithSpouse(func(q *ent.PetQuery) {
					q.WithBadge().WithToys().WithParent(func(q *ent.PetQuery) {
						q.WithBadge().WithToys().WithParent(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						}).WithPlayGroups()
					}).WithPlayGroups()
				}).WithToys().WithParent(func(q *ent.PetQuery) {
					q.WithBadge().WithSpouse(func(q *ent.PetQuery) {
						q.WithBadge().WithToys().WithParent(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						}).WithPlayGroups()
					}).WithToys().WithParent(func(q *ent.PetQuery) {
						q.WithBadge().WithSpouse(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						}).WithToys().WithPlayGroups()
					}).WithPlayGroups()
				}).WithPlayGroups()
			})
		}).WithSpouse(func(q *ent.PetQuery) {
			q.WithBadge().WithProtege(func(q *ent.PetQuery) {
				q.WithBadge().WithToys().WithParent(func(q *ent.PetQuery) {
					q.WithBadge().WithToys().WithParent(func(q *ent.PetQuery) {
						q.WithBadge().WithToys().WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						})
					}).WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
						q.WithBadge().WithToys().WithParent(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						}).WithPlayGroups()
					})
				}).WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
					q.WithBadge().WithToys().WithParent(func(q *ent.PetQuery) {
						q.WithBadge().WithToys().WithParent(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						}).WithPlayGroups()
					}).WithPlayGroups()
				})
			}).WithToys().WithParent(func(q *ent.PetQuery) {
				q.WithBadge().WithProtege(func(q *ent.PetQuery) {
					q.WithBadge().WithToys().WithParent(func(q *ent.PetQuery) {
						q.WithBadge().WithToys().WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						})
					}).WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
						q.WithBadge().WithToys().WithParent(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						}).WithPlayGroups()
					})
				}).WithToys().WithParent(func(q *ent.PetQuery) {
					q.WithBadge().WithProtege(func(q *ent.PetQuery) {
						q.WithBadge().WithToys().WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						})
					}).WithToys().WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
						q.WithBadge().WithProtege(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						}).WithToys().WithPlayGroups()
					})
				}).WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
					q.WithBadge().WithProtege(func(q *ent.PetQuery) {
						q.WithBadge().WithToys().WithParent(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						}).WithPlayGroups()
					}).WithToys().WithParent(func(q *ent.PetQuery) {
						q.WithBadge().WithProtege(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						}).WithToys().WithPlayGroups()
					}).WithPlayGroups()
				})
			}).WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
				q.WithBadge().WithProtege(func(q *ent.PetQuery) {
					q.WithBadge().WithToys().WithParent(func(q *ent.PetQuery) {
						q.WithBadge().WithToys().WithParent(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						}).WithPlayGroups()
					}).WithPlayGroups()
				}).WithToys().WithParent(func(q *ent.PetQuery) {
					q.WithBadge().WithProtege(func(q *ent.PetQuery) {
						q.WithBadge().WithToys().WithParent(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						}).WithPlayGroups()
					}).WithToys().WithParent(func(q *ent.PetQuery) {
						q.WithBadge().WithProtege(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						}).WithToys().WithPlayGroups()
					}).WithPlayGroups()
				}).WithPlayGroups()
			})
		}).WithToys().WithParent(func(q *ent.PetQuery) {
			q.WithBadge().WithProtege(func(q *ent.PetQuery) {
				q.WithBadge().WithSpouse(func(q *ent.PetQuery) {
					q.WithBadge().WithToys().WithParent(func(q *ent.PetQuery) {
						q.WithBadge().WithToys().WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						})
					}).WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
						q.WithBadge().WithToys().WithParent(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						}).WithPlayGroups()
					})
				}).WithToys().WithParent(func(q *ent.PetQuery) {
					q.WithBadge().WithSpouse(func(q *ent.PetQuery) {
						q.WithBadge().WithToys().WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						})
					}).WithToys().WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
						q.WithBadge().WithSpouse(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						}).WithToys().WithPlayGroups()
					})
				}).WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
					q.WithBadge().WithSpouse(func(q *ent.PetQuery) {
						q.WithBadge().WithToys().WithParent(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						}).WithPlayGroups()
					}).WithToys().WithParent(func(q *ent.PetQuery) {
						q.WithBadge().WithSpouse(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						}).WithToys().WithPlayGroups()
					}).WithPlayGroups()
				})
			}).WithSpouse(func(q *ent.PetQuery) {
				q.WithBadge().WithProtege(func(q *ent.PetQuery) {
					q.WithBadge().WithToys().WithParent(func(q *ent.PetQuery) {
						q.WithBadge().WithToys().WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						})
					}).WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
						q.WithBadge().WithToys().WithParent(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						}).WithPlayGroups()
					})
				}).WithToys().WithParent(func(q *ent.PetQuery) {
					q.WithBadge().WithProtege(func(q *ent.PetQuery) {
						q.WithBadge().WithToys().WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						})
					}).WithToys().WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
						q.WithBadge().WithProtege(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						}).WithToys().WithPlayGroups()
					})
				}).WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
					q.WithBadge().WithProtege(func(q *ent.PetQuery) {
						q.WithBadge().WithToys().WithParent(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						}).WithPlayGroups()
					}).WithToys().WithParent(func(q *ent.PetQuery) {
						q.WithBadge().WithProtege(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						}).WithToys().WithPlayGroups()
					}).WithPlayGroups()
				})
			}).WithToys().WithParent(func(q *ent.PetQuery) {
				q.WithBadge().WithProtege(func(q *ent.PetQuery) {
					q.WithBadge().WithSpouse(func(q *ent.PetQuery) {
						q.WithBadge().WithToys().WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						})
					}).WithToys().WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
						q.WithBadge().WithSpouse(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						}).WithToys().WithPlayGroups()
					})
				}).WithSpouse(func(q *ent.PetQuery) {
					q.WithBadge().WithProtege(func(q *ent.PetQuery) {
						q.WithBadge().WithToys().WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						})
					}).WithToys().WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
						q.WithBadge().WithProtege(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						}).WithToys().WithPlayGroups()
					})
				}).WithToys().WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
					q.WithBadge().WithProtege(func(q *ent.PetQuery) {
						q.WithBadge().WithSpouse(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						}).WithToys().WithPlayGroups()
					}).WithSpouse(func(q *ent.PetQuery) {
						q.WithBadge().WithProtege(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						}).WithToys().WithPlayGroups()
					}).WithToys().WithPlayGroups()
				})
			}).WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
				q.WithBadge().WithProtege(func(q *ent.PetQuery) {
					q.WithBadge().WithSpouse(func(q *ent.PetQuery) {
						q.WithBadge().WithToys().WithParent(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						}).WithPlayGroups()
					}).WithToys().WithParent(func(q *ent.PetQuery) {
						q.WithBadge().WithSpouse(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						}).WithToys().WithPlayGroups()
					}).WithPlayGroups()
				}).WithSpouse(func(q *ent.PetQuery) {
					q.WithBadge().WithProtege(func(q *ent.PetQuery) {
						q.WithBadge().WithToys().WithParent(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						}).WithPlayGroups()
					}).WithToys().WithParent(func(q *ent.PetQuery) {
						q.WithBadge().WithProtege(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						}).WithToys().WithPlayGroups()
					}).WithPlayGroups()
				}).WithToys().WithParent(func(q *ent.PetQuery) {
					q.WithBadge().WithProtege(func(q *ent.PetQuery) {
						q.WithBadge().WithSpouse(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						}).WithToys().WithPlayGroups()
					}).WithSpouse(func(q *ent.PetQuery) {
						q.WithBadge().WithProtege(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						}).WithToys().WithPlayGroups()
					}).WithToys().WithPlayGroups()
				}).WithPlayGroups()
			})
		}).WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
			q.WithBadge().WithProtege(func(q *ent.PetQuery) {
				q.WithBadge().WithSpouse(func(q *ent.PetQuery) {
					q.WithBadge().WithToys().WithParent(func(q *ent.PetQuery) {
						q.WithBadge().WithToys().WithParent(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						}).WithPlayGroups()
					}).WithPlayGroups()
				}).WithToys().WithParent(func(q *ent.PetQuery) {
					q.WithBadge().WithSpouse(func(q *ent.PetQuery) {
						q.WithBadge().WithToys().WithParent(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						}).WithPlayGroups()
					}).WithToys().WithParent(func(q *ent.PetQuery) {
						q.WithBadge().WithSpouse(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						}).WithToys().WithPlayGroups()
					}).WithPlayGroups()
				}).WithPlayGroups()
			}).WithSpouse(func(q *ent.PetQuery) {
				q.WithBadge().WithProtege(func(q *ent.PetQuery) {
					q.WithBadge().WithToys().WithParent(func(q *ent.PetQuery) {
						q.WithBadge().WithToys().WithParent(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						}).WithPlayGroups()
					}).WithPlayGroups()
				}).WithToys().WithParent(func(q *ent.PetQuery) {
					q.WithBadge().WithProtege(func(q *ent.PetQuery) {
						q.WithBadge().WithToys().WithParent(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						}).WithPlayGroups()
					}).WithToys().WithParent(func(q *ent.PetQuery) {
						q.WithBadge().WithProtege(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						}).WithToys().WithPlayGroups()
					}).WithPlayGroups()
				}).WithPlayGroups()
			}).WithToys().WithParent(func(q *ent.PetQuery) {
				q.WithBadge().WithProtege(func(q *ent.PetQuery) {
					q.WithBadge().WithSpouse(func(q *ent.PetQuery) {
						q.WithBadge().WithToys().WithParent(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						}).WithPlayGroups()
					}).WithToys().WithParent(func(q *ent.PetQuery) {
						q.WithBadge().WithSpouse(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						}).WithToys().WithPlayGroups()
					}).WithPlayGroups()
				}).WithSpouse(func(q *ent.PetQuery) {
					q.WithBadge().WithProtege(func(q *ent.PetQuery) {
						q.WithBadge().WithToys().WithParent(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						}).WithPlayGroups()
					}).WithToys().WithParent(func(q *ent.PetQuery) {
						q.WithBadge().WithProtege(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						}).WithToys().WithPlayGroups()
					}).WithPlayGroups()
				}).WithToys().WithParent(func(q *ent.PetQuery) {
					q.WithBadge().WithProtege(func(q *ent.PetQuery) {
						q.WithBadge().WithSpouse(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						}).WithToys().WithPlayGroups()
					}).WithSpouse(func(q *ent.PetQuery) {
						q.WithBadge().WithProtege(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						}).WithToys().WithPlayGroups()
					}).WithToys().WithPlayGroups()
				}).WithPlayGroups()
			}).WithPlayGroups()
		})
	})

	e, err := q.Only(r.Context())
	if err != nil {
		switch {
		case ent.IsNotFound(err):
			msg := stripEntError(err)
			l.Info(msg, zap.Error(err), zap.Int("id", id))
			c.Status(404).SendString(msg)
		case ent.IsNotSingular(err):
			msg := stripEntError(err)
			l.Error(msg, zap.Error(err), zap.Int("id", id))
			c.Status(400).SendString(msg)
		default:
			l.Error("could-not-read-badge", zap.Error(err), zap.Int("id", id))
			c.Status(fiber.StatusInternalServerError).SendString("Serve Error")
		}
		return nil
	}
	l.Info("pet rendered", zap.Int("id", e.ID))
	return c.JSON(NewPet340207500View(e))
}

const (
	BadgeCreateRoute Routes = 1 << iota
	BadgeReadRoute
	BadgeUpdateRoute
	BadgeDeleteRoute
	BadgeListRoute
	BadgeWearerRoute
	BadgeRoutes = 1<<iota - 1
)

// BadgeHandler handles http crud operations on ent.Badge.
type BadgeHandler struct {
	handler

	client *ent.Client
	log    *zap.Logger
}

func NewBadgeHandler(c *ent.Client, l *zap.Logger) *BadgeHandler {
	return &BadgeHandler{
		client: c,
		log:    l.With(zap.String("handler", "BadgeHandler")),
	}
}

// RegisterHandlers registers the generated handlers on the given chi router.
func (h *BadgeHandler) Mount(r fiber.Router, rs Routes) {
	if rs.has(BadgeCreateRoute) {
		r.Post("/", h.Create)
	}
	if rs.has(BadgeReadRoute) {
		r.Get("/:id", h.Read)
	}
	if rs.has(BadgeUpdateRoute) {
		r.Patch("/:id", h.Update)
	}
	if rs.has(BadgeDeleteRoute) {
		r.Delete("/:id", h.Delete)
	}
	if rs.has(BadgeListRoute) {
		r.Get("/", h.List)
	}
	if rs.has(BadgeWearerRoute) {
		r.Get("/:id/wearer", h.Wearer)
	}
}
