// Copyright 2019-present Facebook
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// Code generated by entc, DO NOT EDIT.

package ent

import (
	"net/http"
	"strconv"

	"entgo.io/ent/entc/integration/ent"
	"github.com/gofiber/fiber/v2"
	"github.com/masseelch/elk/internal/integration/pets/ent/toy"
	"github.com/valyala/fasthttp/fasthttpadaptor"
	"go.uber.org/zap"
)

// @Summary Read a Toy
// @Description Read a Toy
// @ID Read a Toy
// @Tags [Toy]
// @Accept  json
// @Produce  json
// @Param id path int true "Toy ID"
// @Success 200 {object} ent.Toy
// @Failure 400 {object} main.HTTPError
// @Failure 404 {object} main.HTTPError
// @Failure 500 {object} main.HTTPError
// @Router /toy/{id} [get]
// Read fetches the ent.Toy identified by a given url-parameter from the
// database and renders it to the client.
func (h *ToyHandler) Read(c *fiber.Ctx) error {
	l := h.log.With(zap.String("method", "Read"))
	// ID is URL parameter.
	id, err := strconv.Atoi(c.Params("id"))
	if err != nil {
		l.Error("error getting id from url parameter", zap.String("id", c.Params("id")), zap.Error(err))
		return c.Status(400).SendString("id must be an integer greater zero")
	}
	var r http.Request
	fasthttpadaptor.ConvertRequest(c.Context(), &r, true)
	// Create the query to fetch the Toy
	q := h.client.Toy.Query().Where(toy.ID(id))
	e, err := q.Only(r.Context())
	if err != nil {
		switch {
		case ent.IsNotFound(err):
			msg := stripEntError(err)
			l.Info(msg, zap.Error(err), zap.Int("id", id))
			c.Status(404).SendString(msg)
		case ent.IsNotSingular(err):
			msg := stripEntError(err)
			l.Error(msg, zap.Error(err), zap.Int("id", id))
			c.Status(400).SendString(msg)
		default:
			l.Error("could not read toy", zap.Error(err), zap.Int("id", id))
			c.Status(fiber.StatusInternalServerError).SendString("Serve Error")
		}
		return nil
	}
	l.Info("toy rendered", zap.Int("id", id))
	return c.JSON(NewToy36157710View(e))
}

// Payload of a ent.Toy create request.
type ToyCreateRequest struct {
	Color    *toy.Color    `json:"color"`
	Material *toy.Material `json:"material"`
	Title    *string       `json:"title"`
	Owner    *int          `json:"owner"`
}

// @Summary Create a Toy
// @Description create a Toy
// @ID Create new Toy
// @Tags [Toy]
// @Accept  json
// @Produce  json
// @Success 200 {object} ent.Toy
// @Failure 400 {object} main.HTTPError
// @Failure 404 {object} main.HTTPError
// @Failure 500 {object} main.HTTPError
// @Router /toy [post]
// Create creates a new ent.Toy and stores it in the database.
func (h ToyHandler) Create(c *fiber.Ctx) error {
	l := h.log.With(zap.String("method", "Create"))
	// Get the post data.
	d := new(ToyCreateRequest)
	var r http.Request
	fasthttpadaptor.ConvertRequest(c.Context(), &r, true)

	if err := c.BodyParser(d); err != nil {
		l.Error("error decoding json", zap.Error(err))
		return c.Status(400).SendString("invalid json string")
	}
	// Save the data.
	b := h.client.Toy.Create()
	if d.Color != nil {
		b.SetColor(*d.Color)
	}
	if d.Material != nil {
		b.SetMaterial(*d.Material)
	}
	if d.Title != nil {
		b.SetTitle(*d.Title)
	}
	if d.Owner != nil {
		b.SetOwnerID(*d.Owner)
	}
	e, err := b.Save(r.Context())
	if err != nil {
		switch {
		default:
			l.Error("could not create toy", zap.Error(err))
			c.Status(fiber.StatusInternalServerError).SendString("Serve Error")
		}
		return nil
	}
	// Reload entry.
	q := h.client.Toy.Query().Where(toy.ID(e.ID))
	e, err = q.Only(r.Context())
	if err != nil {
		switch {
		case ent.IsNotFound(err):
			msg := stripEntError(err)
			l.Info(msg, zap.Error(err), zap.Int("id", e.ID))
			c.Status(404).SendString(msg)
		case ent.IsNotSingular(err):
			msg := stripEntError(err)
			l.Error(msg, zap.Error(err), zap.Int("id", e.ID))
			c.Status(400).SendString(msg)
		default:
			l.Error("could not read toy", zap.Error(err), zap.Int("id", e.ID))
			c.Status(fiber.StatusInternalServerError).SendString("Serve Error")
		}
		return nil
	}
	l.Info("toy rendered", zap.Int("id", e.ID))
	return c.JSON(NewToy36157710View(e))
}

// @Summary Delete a Toy
// @Description Delete a Toy
// @ID Delete a Toy
// @Tags [Toy]
// @Accept  json
// @Produce  json
// @Param id path int true "Toy ID"
// @Success 200 {object} ent.Toy
// @Failure 400 {object} main.HTTPError
// @Failure 404 {object} main.HTTPError
// @Failure 500 {object} main.HTTPError
// @Router /toy/{id} [delete]
// Delete removes a ent.Toy from the database.
func (h ToyHandler) Delete(c *fiber.Ctx) error {
	l := h.log.With(zap.String("method", "Delete"))
	// ID is URL parameter.
	id, err := strconv.Atoi(c.Params("id"))
	if err != nil {
		l.Error("error getting id from url parameter", zap.String("id", c.Params("id")), zap.Error(err))
		return c.Status(400).SendString("id must be an integer greater zero")
	}
	var r http.Request
	fasthttpadaptor.ConvertRequest(c.Context(), &r, true)
	err = h.client.Toy.DeleteOneID(id).Exec(r.Context())
	if err != nil {
		switch {
		case ent.IsNotFound(err):
			msg := stripEntError(err)
			l.Info(msg, zap.Error(err), zap.Int("id", id))
			c.Status(404).SendString(msg)
		default:
			l.Error("could-not-delete-toy", zap.Error(err), zap.Int("id", id))
			c.Status(fiber.StatusInternalServerError).SendString("Serve Error")
		}
		return nil
	}
	l.Info("toy deleted", zap.Int("id", id))
	return c.SendString("Delete successfully")
}

// @Summary Fetches Toy
// @Description Fetches Toy
// @ID Fetches Toy
// @Tags [Toy]
// @Accept  json
// @Produce  json
// @Success 200 {array} ent.Toy
// @Failure 400 {object} main.HTTPError
// @Failure 404 {object} main.HTTPError
// @Failure 500 {object} main.HTTPError
// @Router /toy [get]
// Read fetches the ent.Toy identified by a given url-parameter from the
// database and returns it to the client.
func (h *ToyHandler) List(c *fiber.Ctx) error {
	l := h.log.With(zap.String("method", "List"))
	q := h.client.Toy.Query()
	var r http.Request
	fasthttpadaptor.ConvertRequest(c.Context(), &r, true)
	var err error
	page := 1
	if d := c.Query("page"); d != "" {
		page, err = strconv.Atoi(d)
		if err != nil {
			l.Info("error parsing query parameter 'page'", zap.String("page", d), zap.Error(err))
			return c.Status(400).SendString("page must be an integer greater zero")
		}
	}
	itemsPerPage := 30
	if d := c.Query("itemsPerPage"); d != "" {
		itemsPerPage, err = strconv.Atoi(d)
		if err != nil {
			l.Info("error parsing query parameter 'itemsPerPage'", zap.String("itemsPerPage", d), zap.Error(err))
			return c.Status(400).SendString("itemsPerPage must be an integer greater zero")
		}
	}
	es, err := q.Limit(itemsPerPage).Offset((page - 1) * itemsPerPage).All(r.Context())
	if err != nil {
		l.Error("error fetching toys from db", zap.Error(err))
		return c.Status(fiber.StatusInternalServerError).SendString("Serve Error")
	}
	l.Info("toys rendered", zap.Int("amount", len(es)))
	return c.JSON(NewToy36157710Views(es))
}

// Payload of a ent.Toy update request.
type ToyUpdateRequest struct {
	Color    *toy.Color    `json:"color"`
	Material *toy.Material `json:"material"`
	Title    *string       `json:"title"`
	Owner    *int          `json:"owner"`
}

// @Summary Update a Toy
// @Description Update a Toy
// @ID Update a Toy
// @Tags [Toy]
// @Accept  json
// @Produce  json
// @Param id path int true "Toy ID"
// @Success 200 {object} ent.Toy
// @Failure 400 {object} main.HTTPError
// @Failure 404 {object} main.HTTPError
// @Failure 500 {object} main.HTTPError
// @Router /toy/{id} [patch]
// Update updates a given ent.Toy and saves the changes to the database.
func (h ToyHandler) Update(c *fiber.Ctx) error {
	l := h.log.With(zap.String("method", "Update"))
	// ID is URL parameter.
	id, err := strconv.Atoi(c.Params("id"))
	if err != nil {
		l.Error("error getting id from url parameter", zap.String("id", c.Params("id")), zap.Error(err))
		return c.Status(400).SendString("id must be an integer greater zero")
	}
	// Get the post data.
	d := new(ToyUpdateRequest)
	var r http.Request
	fasthttpadaptor.ConvertRequest(c.Context(), &r, true)

	if err := c.BodyParser(d); err != nil {
		l.Error("error decoding json", zap.Error(err))
		return c.Status(400).SendString("invalid json string")
	}
	// Save the data.
	b := h.client.Toy.UpdateOneID(id)
	if d.Color != nil {
		b.SetColor(*d.Color)
	}
	if d.Material != nil {
		b.SetMaterial(*d.Material)
	}
	if d.Title != nil {
		b.SetTitle(*d.Title)
	}
	if d.Owner != nil {
		b.SetOwnerID(*d.Owner)

	}
	// Store in database.
	e, err := b.Save(r.Context())
	if err != nil {
		switch {
		case ent.IsNotFound(err):
			msg := stripEntError(err)
			l.Info(msg, zap.Error(err), zap.Int("id", id))
			c.Status(404).SendString(msg)
		case ent.IsNotSingular(err):
			msg := stripEntError(err)
			l.Error(msg, zap.Error(err), zap.Int("id", id))
			c.Status(400).SendString(msg)
		default:
			l.Error("could-not-update-toy", zap.Error(err), zap.Int("id", id))
			c.Status(fiber.StatusInternalServerError).SendString("Serve Error")
		}
		return nil
	}
	// Reload entry.
	q := h.client.Toy.Query().Where(toy.ID(e.ID))
	e, err = q.Only(r.Context())
	if err != nil {
		switch {
		case ent.IsNotFound(err):
			msg := stripEntError(err)
			l.Info(msg, zap.Error(err), zap.Int("id", id))
			c.Status(404).SendString(msg)
		case ent.IsNotSingular(err):
			msg := stripEntError(err)
			l.Error(msg, zap.Error(err), zap.Int("id", id))
			c.Status(400).SendString(msg)
		default:
			l.Error("could-not-read-toy", zap.Error(err), zap.Int("id", id))
			c.Status(fiber.StatusInternalServerError).SendString("Serve Error")
		}
		return nil
	}
	l.Info("toy rendered", zap.Int("id", e.ID))
	return c.JSON(NewToy36157710View(e))
}

// @Summary Get Toy with Owner
// @Description Get Toy with Owner
// @ID Get Toy with Owner
// @Tags [Toy]
// @Accept  json
// @Produce  json
// @Param id path int true "Toy ID"
// @Success 200 {object} ent.Toy
// @Failure 400 {object} main.HTTPError
// @Failure 404 {object} main.HTTPError
// @Failure 500 {object} main.HTTPError
// @Router /toy/{id}/owner [get]
// Owner fetches the ent.owner attached to the ent.Toy
// identified by a given url-parameter from the database and renders it to the client.
func (h ToyHandler) Owner(c *fiber.Ctx) error {
	l := h.log.With(zap.String("method", "Owner"))
	// ID is URL parameter.
	id, err := strconv.Atoi(c.Params("id"))
	if err != nil {
		l.Error("error getting id from url parameter", zap.String("id", c.Params("id")), zap.Error(err))
		return c.Status(400).SendString("id must be an integer greater zero")
	}
	var r http.Request
	fasthttpadaptor.ConvertRequest(c.Context(), &r, true)
	// Create the query to fetch the owner attached to this toy
	q := h.client.Toy.Query().Where(toy.ID(id)).QueryOwner()
	// Eager load edges that are required on read operation.
	q.WithBadge().WithProtege(func(q *ent.PetQuery) {
		q.WithBadge().WithSpouse(func(q *ent.PetQuery) {
			q.WithBadge().WithToys().WithParent(func(q *ent.PetQuery) {
				q.WithBadge().WithToys().WithParent(func(q *ent.PetQuery) {
					q.WithBadge().WithToys().WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
						q.WithBadge().WithToys().WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						})
					})
				}).WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
					q.WithBadge().WithToys().WithParent(func(q *ent.PetQuery) {
						q.WithBadge().WithToys().WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						})
					}).WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
						q.WithBadge().WithToys().WithParent(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						}).WithPlayGroups()
					})
				})
			}).WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
				q.WithBadge().WithToys().WithParent(func(q *ent.PetQuery) {
					q.WithBadge().WithToys().WithParent(func(q *ent.PetQuery) {
						q.WithBadge().WithToys().WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						})
					}).WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
						q.WithBadge().WithToys().WithParent(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						}).WithPlayGroups()
					})
				}).WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
					q.WithBadge().WithToys().WithParent(func(q *ent.PetQuery) {
						q.WithBadge().WithToys().WithParent(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						}).WithPlayGroups()
					}).WithPlayGroups()
				})
			})
		}).WithToys().WithParent(func(q *ent.PetQuery) {
			q.WithBadge().WithSpouse(func(q *ent.PetQuery) {
				q.WithBadge().WithToys().WithParent(func(q *ent.PetQuery) {
					q.WithBadge().WithToys().WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
						q.WithBadge().WithToys().WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						})
					})
				}).WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
					q.WithBadge().WithToys().WithParent(func(q *ent.PetQuery) {
						q.WithBadge().WithToys().WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						})
					}).WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
						q.WithBadge().WithToys().WithParent(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						}).WithPlayGroups()
					})
				})
			}).WithToys().WithParent(func(q *ent.PetQuery) {
				q.WithBadge().WithSpouse(func(q *ent.PetQuery) {
					q.WithBadge().WithToys().WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
						q.WithBadge().WithToys().WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						})
					})
				}).WithToys().WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
					q.WithBadge().WithSpouse(func(q *ent.PetQuery) {
						q.WithBadge().WithToys().WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						})
					}).WithToys().WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
						q.WithBadge().WithSpouse(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						}).WithToys().WithPlayGroups()
					})
				})
			}).WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
				q.WithBadge().WithSpouse(func(q *ent.PetQuery) {
					q.WithBadge().WithToys().WithParent(func(q *ent.PetQuery) {
						q.WithBadge().WithToys().WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						})
					}).WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
						q.WithBadge().WithToys().WithParent(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						}).WithPlayGroups()
					})
				}).WithToys().WithParent(func(q *ent.PetQuery) {
					q.WithBadge().WithSpouse(func(q *ent.PetQuery) {
						q.WithBadge().WithToys().WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						})
					}).WithToys().WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
						q.WithBadge().WithSpouse(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						}).WithToys().WithPlayGroups()
					})
				}).WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
					q.WithBadge().WithSpouse(func(q *ent.PetQuery) {
						q.WithBadge().WithToys().WithParent(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						}).WithPlayGroups()
					}).WithToys().WithParent(func(q *ent.PetQuery) {
						q.WithBadge().WithSpouse(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						}).WithToys().WithPlayGroups()
					}).WithPlayGroups()
				})
			})
		}).WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
			q.WithBadge().WithSpouse(func(q *ent.PetQuery) {
				q.WithBadge().WithToys().WithParent(func(q *ent.PetQuery) {
					q.WithBadge().WithToys().WithParent(func(q *ent.PetQuery) {
						q.WithBadge().WithToys().WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						})
					}).WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
						q.WithBadge().WithToys().WithParent(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						}).WithPlayGroups()
					})
				}).WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
					q.WithBadge().WithToys().WithParent(func(q *ent.PetQuery) {
						q.WithBadge().WithToys().WithParent(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						}).WithPlayGroups()
					}).WithPlayGroups()
				})
			}).WithToys().WithParent(func(q *ent.PetQuery) {
				q.WithBadge().WithSpouse(func(q *ent.PetQuery) {
					q.WithBadge().WithToys().WithParent(func(q *ent.PetQuery) {
						q.WithBadge().WithToys().WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						})
					}).WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
						q.WithBadge().WithToys().WithParent(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						}).WithPlayGroups()
					})
				}).WithToys().WithParent(func(q *ent.PetQuery) {
					q.WithBadge().WithSpouse(func(q *ent.PetQuery) {
						q.WithBadge().WithToys().WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						})
					}).WithToys().WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
						q.WithBadge().WithSpouse(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						}).WithToys().WithPlayGroups()
					})
				}).WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
					q.WithBadge().WithSpouse(func(q *ent.PetQuery) {
						q.WithBadge().WithToys().WithParent(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						}).WithPlayGroups()
					}).WithToys().WithParent(func(q *ent.PetQuery) {
						q.WithBadge().WithSpouse(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						}).WithToys().WithPlayGroups()
					}).WithPlayGroups()
				})
			}).WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
				q.WithBadge().WithSpouse(func(q *ent.PetQuery) {
					q.WithBadge().WithToys().WithParent(func(q *ent.PetQuery) {
						q.WithBadge().WithToys().WithParent(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						}).WithPlayGroups()
					}).WithPlayGroups()
				}).WithToys().WithParent(func(q *ent.PetQuery) {
					q.WithBadge().WithSpouse(func(q *ent.PetQuery) {
						q.WithBadge().WithToys().WithParent(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						}).WithPlayGroups()
					}).WithToys().WithParent(func(q *ent.PetQuery) {
						q.WithBadge().WithSpouse(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						}).WithToys().WithPlayGroups()
					}).WithPlayGroups()
				}).WithPlayGroups()
			})
		})
	}).WithSpouse(func(q *ent.PetQuery) {
		q.WithBadge().WithProtege(func(q *ent.PetQuery) {
			q.WithBadge().WithToys().WithParent(func(q *ent.PetQuery) {
				q.WithBadge().WithToys().WithParent(func(q *ent.PetQuery) {
					q.WithBadge().WithToys().WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
						q.WithBadge().WithToys().WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						})
					})
				}).WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
					q.WithBadge().WithToys().WithParent(func(q *ent.PetQuery) {
						q.WithBadge().WithToys().WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						})
					}).WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
						q.WithBadge().WithToys().WithParent(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						}).WithPlayGroups()
					})
				})
			}).WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
				q.WithBadge().WithToys().WithParent(func(q *ent.PetQuery) {
					q.WithBadge().WithToys().WithParent(func(q *ent.PetQuery) {
						q.WithBadge().WithToys().WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						})
					}).WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
						q.WithBadge().WithToys().WithParent(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						}).WithPlayGroups()
					})
				}).WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
					q.WithBadge().WithToys().WithParent(func(q *ent.PetQuery) {
						q.WithBadge().WithToys().WithParent(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						}).WithPlayGroups()
					}).WithPlayGroups()
				})
			})
		}).WithToys().WithParent(func(q *ent.PetQuery) {
			q.WithBadge().WithProtege(func(q *ent.PetQuery) {
				q.WithBadge().WithToys().WithParent(func(q *ent.PetQuery) {
					q.WithBadge().WithToys().WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
						q.WithBadge().WithToys().WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						})
					})
				}).WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
					q.WithBadge().WithToys().WithParent(func(q *ent.PetQuery) {
						q.WithBadge().WithToys().WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						})
					}).WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
						q.WithBadge().WithToys().WithParent(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						}).WithPlayGroups()
					})
				})
			}).WithToys().WithParent(func(q *ent.PetQuery) {
				q.WithBadge().WithProtege(func(q *ent.PetQuery) {
					q.WithBadge().WithToys().WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
						q.WithBadge().WithToys().WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						})
					})
				}).WithToys().WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
					q.WithBadge().WithProtege(func(q *ent.PetQuery) {
						q.WithBadge().WithToys().WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						})
					}).WithToys().WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
						q.WithBadge().WithProtege(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						}).WithToys().WithPlayGroups()
					})
				})
			}).WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
				q.WithBadge().WithProtege(func(q *ent.PetQuery) {
					q.WithBadge().WithToys().WithParent(func(q *ent.PetQuery) {
						q.WithBadge().WithToys().WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						})
					}).WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
						q.WithBadge().WithToys().WithParent(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						}).WithPlayGroups()
					})
				}).WithToys().WithParent(func(q *ent.PetQuery) {
					q.WithBadge().WithProtege(func(q *ent.PetQuery) {
						q.WithBadge().WithToys().WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						})
					}).WithToys().WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
						q.WithBadge().WithProtege(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						}).WithToys().WithPlayGroups()
					})
				}).WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
					q.WithBadge().WithProtege(func(q *ent.PetQuery) {
						q.WithBadge().WithToys().WithParent(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						}).WithPlayGroups()
					}).WithToys().WithParent(func(q *ent.PetQuery) {
						q.WithBadge().WithProtege(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						}).WithToys().WithPlayGroups()
					}).WithPlayGroups()
				})
			})
		}).WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
			q.WithBadge().WithProtege(func(q *ent.PetQuery) {
				q.WithBadge().WithToys().WithParent(func(q *ent.PetQuery) {
					q.WithBadge().WithToys().WithParent(func(q *ent.PetQuery) {
						q.WithBadge().WithToys().WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						})
					}).WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
						q.WithBadge().WithToys().WithParent(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						}).WithPlayGroups()
					})
				}).WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
					q.WithBadge().WithToys().WithParent(func(q *ent.PetQuery) {
						q.WithBadge().WithToys().WithParent(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						}).WithPlayGroups()
					}).WithPlayGroups()
				})
			}).WithToys().WithParent(func(q *ent.PetQuery) {
				q.WithBadge().WithProtege(func(q *ent.PetQuery) {
					q.WithBadge().WithToys().WithParent(func(q *ent.PetQuery) {
						q.WithBadge().WithToys().WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						})
					}).WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
						q.WithBadge().WithToys().WithParent(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						}).WithPlayGroups()
					})
				}).WithToys().WithParent(func(q *ent.PetQuery) {
					q.WithBadge().WithProtege(func(q *ent.PetQuery) {
						q.WithBadge().WithToys().WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						})
					}).WithToys().WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
						q.WithBadge().WithProtege(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						}).WithToys().WithPlayGroups()
					})
				}).WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
					q.WithBadge().WithProtege(func(q *ent.PetQuery) {
						q.WithBadge().WithToys().WithParent(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						}).WithPlayGroups()
					}).WithToys().WithParent(func(q *ent.PetQuery) {
						q.WithBadge().WithProtege(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						}).WithToys().WithPlayGroups()
					}).WithPlayGroups()
				})
			}).WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
				q.WithBadge().WithProtege(func(q *ent.PetQuery) {
					q.WithBadge().WithToys().WithParent(func(q *ent.PetQuery) {
						q.WithBadge().WithToys().WithParent(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						}).WithPlayGroups()
					}).WithPlayGroups()
				}).WithToys().WithParent(func(q *ent.PetQuery) {
					q.WithBadge().WithProtege(func(q *ent.PetQuery) {
						q.WithBadge().WithToys().WithParent(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						}).WithPlayGroups()
					}).WithToys().WithParent(func(q *ent.PetQuery) {
						q.WithBadge().WithProtege(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						}).WithToys().WithPlayGroups()
					}).WithPlayGroups()
				}).WithPlayGroups()
			})
		})
	}).WithToys().WithParent(func(q *ent.PetQuery) {
		q.WithBadge().WithProtege(func(q *ent.PetQuery) {
			q.WithBadge().WithSpouse(func(q *ent.PetQuery) {
				q.WithBadge().WithToys().WithParent(func(q *ent.PetQuery) {
					q.WithBadge().WithToys().WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
						q.WithBadge().WithToys().WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						})
					})
				}).WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
					q.WithBadge().WithToys().WithParent(func(q *ent.PetQuery) {
						q.WithBadge().WithToys().WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						})
					}).WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
						q.WithBadge().WithToys().WithParent(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						}).WithPlayGroups()
					})
				})
			}).WithToys().WithParent(func(q *ent.PetQuery) {
				q.WithBadge().WithSpouse(func(q *ent.PetQuery) {
					q.WithBadge().WithToys().WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
						q.WithBadge().WithToys().WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						})
					})
				}).WithToys().WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
					q.WithBadge().WithSpouse(func(q *ent.PetQuery) {
						q.WithBadge().WithToys().WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						})
					}).WithToys().WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
						q.WithBadge().WithSpouse(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						}).WithToys().WithPlayGroups()
					})
				})
			}).WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
				q.WithBadge().WithSpouse(func(q *ent.PetQuery) {
					q.WithBadge().WithToys().WithParent(func(q *ent.PetQuery) {
						q.WithBadge().WithToys().WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						})
					}).WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
						q.WithBadge().WithToys().WithParent(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						}).WithPlayGroups()
					})
				}).WithToys().WithParent(func(q *ent.PetQuery) {
					q.WithBadge().WithSpouse(func(q *ent.PetQuery) {
						q.WithBadge().WithToys().WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						})
					}).WithToys().WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
						q.WithBadge().WithSpouse(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						}).WithToys().WithPlayGroups()
					})
				}).WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
					q.WithBadge().WithSpouse(func(q *ent.PetQuery) {
						q.WithBadge().WithToys().WithParent(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						}).WithPlayGroups()
					}).WithToys().WithParent(func(q *ent.PetQuery) {
						q.WithBadge().WithSpouse(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						}).WithToys().WithPlayGroups()
					}).WithPlayGroups()
				})
			})
		}).WithSpouse(func(q *ent.PetQuery) {
			q.WithBadge().WithProtege(func(q *ent.PetQuery) {
				q.WithBadge().WithToys().WithParent(func(q *ent.PetQuery) {
					q.WithBadge().WithToys().WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
						q.WithBadge().WithToys().WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						})
					})
				}).WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
					q.WithBadge().WithToys().WithParent(func(q *ent.PetQuery) {
						q.WithBadge().WithToys().WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						})
					}).WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
						q.WithBadge().WithToys().WithParent(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						}).WithPlayGroups()
					})
				})
			}).WithToys().WithParent(func(q *ent.PetQuery) {
				q.WithBadge().WithProtege(func(q *ent.PetQuery) {
					q.WithBadge().WithToys().WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
						q.WithBadge().WithToys().WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						})
					})
				}).WithToys().WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
					q.WithBadge().WithProtege(func(q *ent.PetQuery) {
						q.WithBadge().WithToys().WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						})
					}).WithToys().WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
						q.WithBadge().WithProtege(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						}).WithToys().WithPlayGroups()
					})
				})
			}).WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
				q.WithBadge().WithProtege(func(q *ent.PetQuery) {
					q.WithBadge().WithToys().WithParent(func(q *ent.PetQuery) {
						q.WithBadge().WithToys().WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						})
					}).WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
						q.WithBadge().WithToys().WithParent(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						}).WithPlayGroups()
					})
				}).WithToys().WithParent(func(q *ent.PetQuery) {
					q.WithBadge().WithProtege(func(q *ent.PetQuery) {
						q.WithBadge().WithToys().WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						})
					}).WithToys().WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
						q.WithBadge().WithProtege(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						}).WithToys().WithPlayGroups()
					})
				}).WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
					q.WithBadge().WithProtege(func(q *ent.PetQuery) {
						q.WithBadge().WithToys().WithParent(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						}).WithPlayGroups()
					}).WithToys().WithParent(func(q *ent.PetQuery) {
						q.WithBadge().WithProtege(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						}).WithToys().WithPlayGroups()
					}).WithPlayGroups()
				})
			})
		}).WithToys().WithParent(func(q *ent.PetQuery) {
			q.WithBadge().WithProtege(func(q *ent.PetQuery) {
				q.WithBadge().WithSpouse(func(q *ent.PetQuery) {
					q.WithBadge().WithToys().WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
						q.WithBadge().WithToys().WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						})
					})
				}).WithToys().WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
					q.WithBadge().WithSpouse(func(q *ent.PetQuery) {
						q.WithBadge().WithToys().WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						})
					}).WithToys().WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
						q.WithBadge().WithSpouse(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						}).WithToys().WithPlayGroups()
					})
				})
			}).WithSpouse(func(q *ent.PetQuery) {
				q.WithBadge().WithProtege(func(q *ent.PetQuery) {
					q.WithBadge().WithToys().WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
						q.WithBadge().WithToys().WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						})
					})
				}).WithToys().WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
					q.WithBadge().WithProtege(func(q *ent.PetQuery) {
						q.WithBadge().WithToys().WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						})
					}).WithToys().WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
						q.WithBadge().WithProtege(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						}).WithToys().WithPlayGroups()
					})
				})
			}).WithToys().WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
				q.WithBadge().WithProtege(func(q *ent.PetQuery) {
					q.WithBadge().WithSpouse(func(q *ent.PetQuery) {
						q.WithBadge().WithToys().WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						})
					}).WithToys().WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
						q.WithBadge().WithSpouse(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						}).WithToys().WithPlayGroups()
					})
				}).WithSpouse(func(q *ent.PetQuery) {
					q.WithBadge().WithProtege(func(q *ent.PetQuery) {
						q.WithBadge().WithToys().WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						})
					}).WithToys().WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
						q.WithBadge().WithProtege(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						}).WithToys().WithPlayGroups()
					})
				}).WithToys().WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
					q.WithBadge().WithProtege(func(q *ent.PetQuery) {
						q.WithBadge().WithSpouse(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						}).WithToys().WithPlayGroups()
					}).WithSpouse(func(q *ent.PetQuery) {
						q.WithBadge().WithProtege(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						}).WithToys().WithPlayGroups()
					}).WithToys().WithPlayGroups()
				})
			})
		}).WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
			q.WithBadge().WithProtege(func(q *ent.PetQuery) {
				q.WithBadge().WithSpouse(func(q *ent.PetQuery) {
					q.WithBadge().WithToys().WithParent(func(q *ent.PetQuery) {
						q.WithBadge().WithToys().WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						})
					}).WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
						q.WithBadge().WithToys().WithParent(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						}).WithPlayGroups()
					})
				}).WithToys().WithParent(func(q *ent.PetQuery) {
					q.WithBadge().WithSpouse(func(q *ent.PetQuery) {
						q.WithBadge().WithToys().WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						})
					}).WithToys().WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
						q.WithBadge().WithSpouse(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						}).WithToys().WithPlayGroups()
					})
				}).WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
					q.WithBadge().WithSpouse(func(q *ent.PetQuery) {
						q.WithBadge().WithToys().WithParent(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						}).WithPlayGroups()
					}).WithToys().WithParent(func(q *ent.PetQuery) {
						q.WithBadge().WithSpouse(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						}).WithToys().WithPlayGroups()
					}).WithPlayGroups()
				})
			}).WithSpouse(func(q *ent.PetQuery) {
				q.WithBadge().WithProtege(func(q *ent.PetQuery) {
					q.WithBadge().WithToys().WithParent(func(q *ent.PetQuery) {
						q.WithBadge().WithToys().WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						})
					}).WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
						q.WithBadge().WithToys().WithParent(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						}).WithPlayGroups()
					})
				}).WithToys().WithParent(func(q *ent.PetQuery) {
					q.WithBadge().WithProtege(func(q *ent.PetQuery) {
						q.WithBadge().WithToys().WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						})
					}).WithToys().WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
						q.WithBadge().WithProtege(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						}).WithToys().WithPlayGroups()
					})
				}).WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
					q.WithBadge().WithProtege(func(q *ent.PetQuery) {
						q.WithBadge().WithToys().WithParent(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						}).WithPlayGroups()
					}).WithToys().WithParent(func(q *ent.PetQuery) {
						q.WithBadge().WithProtege(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						}).WithToys().WithPlayGroups()
					}).WithPlayGroups()
				})
			}).WithToys().WithParent(func(q *ent.PetQuery) {
				q.WithBadge().WithProtege(func(q *ent.PetQuery) {
					q.WithBadge().WithSpouse(func(q *ent.PetQuery) {
						q.WithBadge().WithToys().WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						})
					}).WithToys().WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
						q.WithBadge().WithSpouse(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						}).WithToys().WithPlayGroups()
					})
				}).WithSpouse(func(q *ent.PetQuery) {
					q.WithBadge().WithProtege(func(q *ent.PetQuery) {
						q.WithBadge().WithToys().WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						})
					}).WithToys().WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
						q.WithBadge().WithProtege(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						}).WithToys().WithPlayGroups()
					})
				}).WithToys().WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
					q.WithBadge().WithProtege(func(q *ent.PetQuery) {
						q.WithBadge().WithSpouse(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						}).WithToys().WithPlayGroups()
					}).WithSpouse(func(q *ent.PetQuery) {
						q.WithBadge().WithProtege(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						}).WithToys().WithPlayGroups()
					}).WithToys().WithPlayGroups()
				})
			}).WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
				q.WithBadge().WithProtege(func(q *ent.PetQuery) {
					q.WithBadge().WithSpouse(func(q *ent.PetQuery) {
						q.WithBadge().WithToys().WithParent(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						}).WithPlayGroups()
					}).WithToys().WithParent(func(q *ent.PetQuery) {
						q.WithBadge().WithSpouse(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						}).WithToys().WithPlayGroups()
					}).WithPlayGroups()
				}).WithSpouse(func(q *ent.PetQuery) {
					q.WithBadge().WithProtege(func(q *ent.PetQuery) {
						q.WithBadge().WithToys().WithParent(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						}).WithPlayGroups()
					}).WithToys().WithParent(func(q *ent.PetQuery) {
						q.WithBadge().WithProtege(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						}).WithToys().WithPlayGroups()
					}).WithPlayGroups()
				}).WithToys().WithParent(func(q *ent.PetQuery) {
					q.WithBadge().WithProtege(func(q *ent.PetQuery) {
						q.WithBadge().WithSpouse(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						}).WithToys().WithPlayGroups()
					}).WithSpouse(func(q *ent.PetQuery) {
						q.WithBadge().WithProtege(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						}).WithToys().WithPlayGroups()
					}).WithToys().WithPlayGroups()
				}).WithPlayGroups()
			})
		})
	}).WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
		q.WithBadge().WithProtege(func(q *ent.PetQuery) {
			q.WithBadge().WithSpouse(func(q *ent.PetQuery) {
				q.WithBadge().WithToys().WithParent(func(q *ent.PetQuery) {
					q.WithBadge().WithToys().WithParent(func(q *ent.PetQuery) {
						q.WithBadge().WithToys().WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						})
					}).WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
						q.WithBadge().WithToys().WithParent(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						}).WithPlayGroups()
					})
				}).WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
					q.WithBadge().WithToys().WithParent(func(q *ent.PetQuery) {
						q.WithBadge().WithToys().WithParent(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						}).WithPlayGroups()
					}).WithPlayGroups()
				})
			}).WithToys().WithParent(func(q *ent.PetQuery) {
				q.WithBadge().WithSpouse(func(q *ent.PetQuery) {
					q.WithBadge().WithToys().WithParent(func(q *ent.PetQuery) {
						q.WithBadge().WithToys().WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						})
					}).WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
						q.WithBadge().WithToys().WithParent(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						}).WithPlayGroups()
					})
				}).WithToys().WithParent(func(q *ent.PetQuery) {
					q.WithBadge().WithSpouse(func(q *ent.PetQuery) {
						q.WithBadge().WithToys().WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						})
					}).WithToys().WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
						q.WithBadge().WithSpouse(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						}).WithToys().WithPlayGroups()
					})
				}).WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
					q.WithBadge().WithSpouse(func(q *ent.PetQuery) {
						q.WithBadge().WithToys().WithParent(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						}).WithPlayGroups()
					}).WithToys().WithParent(func(q *ent.PetQuery) {
						q.WithBadge().WithSpouse(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						}).WithToys().WithPlayGroups()
					}).WithPlayGroups()
				})
			}).WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
				q.WithBadge().WithSpouse(func(q *ent.PetQuery) {
					q.WithBadge().WithToys().WithParent(func(q *ent.PetQuery) {
						q.WithBadge().WithToys().WithParent(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						}).WithPlayGroups()
					}).WithPlayGroups()
				}).WithToys().WithParent(func(q *ent.PetQuery) {
					q.WithBadge().WithSpouse(func(q *ent.PetQuery) {
						q.WithBadge().WithToys().WithParent(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						}).WithPlayGroups()
					}).WithToys().WithParent(func(q *ent.PetQuery) {
						q.WithBadge().WithSpouse(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						}).WithToys().WithPlayGroups()
					}).WithPlayGroups()
				}).WithPlayGroups()
			})
		}).WithSpouse(func(q *ent.PetQuery) {
			q.WithBadge().WithProtege(func(q *ent.PetQuery) {
				q.WithBadge().WithToys().WithParent(func(q *ent.PetQuery) {
					q.WithBadge().WithToys().WithParent(func(q *ent.PetQuery) {
						q.WithBadge().WithToys().WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						})
					}).WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
						q.WithBadge().WithToys().WithParent(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						}).WithPlayGroups()
					})
				}).WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
					q.WithBadge().WithToys().WithParent(func(q *ent.PetQuery) {
						q.WithBadge().WithToys().WithParent(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						}).WithPlayGroups()
					}).WithPlayGroups()
				})
			}).WithToys().WithParent(func(q *ent.PetQuery) {
				q.WithBadge().WithProtege(func(q *ent.PetQuery) {
					q.WithBadge().WithToys().WithParent(func(q *ent.PetQuery) {
						q.WithBadge().WithToys().WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						})
					}).WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
						q.WithBadge().WithToys().WithParent(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						}).WithPlayGroups()
					})
				}).WithToys().WithParent(func(q *ent.PetQuery) {
					q.WithBadge().WithProtege(func(q *ent.PetQuery) {
						q.WithBadge().WithToys().WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						})
					}).WithToys().WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
						q.WithBadge().WithProtege(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						}).WithToys().WithPlayGroups()
					})
				}).WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
					q.WithBadge().WithProtege(func(q *ent.PetQuery) {
						q.WithBadge().WithToys().WithParent(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						}).WithPlayGroups()
					}).WithToys().WithParent(func(q *ent.PetQuery) {
						q.WithBadge().WithProtege(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						}).WithToys().WithPlayGroups()
					}).WithPlayGroups()
				})
			}).WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
				q.WithBadge().WithProtege(func(q *ent.PetQuery) {
					q.WithBadge().WithToys().WithParent(func(q *ent.PetQuery) {
						q.WithBadge().WithToys().WithParent(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						}).WithPlayGroups()
					}).WithPlayGroups()
				}).WithToys().WithParent(func(q *ent.PetQuery) {
					q.WithBadge().WithProtege(func(q *ent.PetQuery) {
						q.WithBadge().WithToys().WithParent(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						}).WithPlayGroups()
					}).WithToys().WithParent(func(q *ent.PetQuery) {
						q.WithBadge().WithProtege(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						}).WithToys().WithPlayGroups()
					}).WithPlayGroups()
				}).WithPlayGroups()
			})
		}).WithToys().WithParent(func(q *ent.PetQuery) {
			q.WithBadge().WithProtege(func(q *ent.PetQuery) {
				q.WithBadge().WithSpouse(func(q *ent.PetQuery) {
					q.WithBadge().WithToys().WithParent(func(q *ent.PetQuery) {
						q.WithBadge().WithToys().WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						})
					}).WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
						q.WithBadge().WithToys().WithParent(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						}).WithPlayGroups()
					})
				}).WithToys().WithParent(func(q *ent.PetQuery) {
					q.WithBadge().WithSpouse(func(q *ent.PetQuery) {
						q.WithBadge().WithToys().WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						})
					}).WithToys().WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
						q.WithBadge().WithSpouse(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						}).WithToys().WithPlayGroups()
					})
				}).WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
					q.WithBadge().WithSpouse(func(q *ent.PetQuery) {
						q.WithBadge().WithToys().WithParent(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						}).WithPlayGroups()
					}).WithToys().WithParent(func(q *ent.PetQuery) {
						q.WithBadge().WithSpouse(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						}).WithToys().WithPlayGroups()
					}).WithPlayGroups()
				})
			}).WithSpouse(func(q *ent.PetQuery) {
				q.WithBadge().WithProtege(func(q *ent.PetQuery) {
					q.WithBadge().WithToys().WithParent(func(q *ent.PetQuery) {
						q.WithBadge().WithToys().WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						})
					}).WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
						q.WithBadge().WithToys().WithParent(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						}).WithPlayGroups()
					})
				}).WithToys().WithParent(func(q *ent.PetQuery) {
					q.WithBadge().WithProtege(func(q *ent.PetQuery) {
						q.WithBadge().WithToys().WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						})
					}).WithToys().WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
						q.WithBadge().WithProtege(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						}).WithToys().WithPlayGroups()
					})
				}).WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
					q.WithBadge().WithProtege(func(q *ent.PetQuery) {
						q.WithBadge().WithToys().WithParent(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						}).WithPlayGroups()
					}).WithToys().WithParent(func(q *ent.PetQuery) {
						q.WithBadge().WithProtege(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						}).WithToys().WithPlayGroups()
					}).WithPlayGroups()
				})
			}).WithToys().WithParent(func(q *ent.PetQuery) {
				q.WithBadge().WithProtege(func(q *ent.PetQuery) {
					q.WithBadge().WithSpouse(func(q *ent.PetQuery) {
						q.WithBadge().WithToys().WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						})
					}).WithToys().WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
						q.WithBadge().WithSpouse(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						}).WithToys().WithPlayGroups()
					})
				}).WithSpouse(func(q *ent.PetQuery) {
					q.WithBadge().WithProtege(func(q *ent.PetQuery) {
						q.WithBadge().WithToys().WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						})
					}).WithToys().WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
						q.WithBadge().WithProtege(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						}).WithToys().WithPlayGroups()
					})
				}).WithToys().WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
					q.WithBadge().WithProtege(func(q *ent.PetQuery) {
						q.WithBadge().WithSpouse(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						}).WithToys().WithPlayGroups()
					}).WithSpouse(func(q *ent.PetQuery) {
						q.WithBadge().WithProtege(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						}).WithToys().WithPlayGroups()
					}).WithToys().WithPlayGroups()
				})
			}).WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
				q.WithBadge().WithProtege(func(q *ent.PetQuery) {
					q.WithBadge().WithSpouse(func(q *ent.PetQuery) {
						q.WithBadge().WithToys().WithParent(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						}).WithPlayGroups()
					}).WithToys().WithParent(func(q *ent.PetQuery) {
						q.WithBadge().WithSpouse(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						}).WithToys().WithPlayGroups()
					}).WithPlayGroups()
				}).WithSpouse(func(q *ent.PetQuery) {
					q.WithBadge().WithProtege(func(q *ent.PetQuery) {
						q.WithBadge().WithToys().WithParent(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						}).WithPlayGroups()
					}).WithToys().WithParent(func(q *ent.PetQuery) {
						q.WithBadge().WithProtege(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						}).WithToys().WithPlayGroups()
					}).WithPlayGroups()
				}).WithToys().WithParent(func(q *ent.PetQuery) {
					q.WithBadge().WithProtege(func(q *ent.PetQuery) {
						q.WithBadge().WithSpouse(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						}).WithToys().WithPlayGroups()
					}).WithSpouse(func(q *ent.PetQuery) {
						q.WithBadge().WithProtege(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						}).WithToys().WithPlayGroups()
					}).WithToys().WithPlayGroups()
				}).WithPlayGroups()
			})
		}).WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
			q.WithBadge().WithProtege(func(q *ent.PetQuery) {
				q.WithBadge().WithSpouse(func(q *ent.PetQuery) {
					q.WithBadge().WithToys().WithParent(func(q *ent.PetQuery) {
						q.WithBadge().WithToys().WithParent(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						}).WithPlayGroups()
					}).WithPlayGroups()
				}).WithToys().WithParent(func(q *ent.PetQuery) {
					q.WithBadge().WithSpouse(func(q *ent.PetQuery) {
						q.WithBadge().WithToys().WithParent(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						}).WithPlayGroups()
					}).WithToys().WithParent(func(q *ent.PetQuery) {
						q.WithBadge().WithSpouse(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						}).WithToys().WithPlayGroups()
					}).WithPlayGroups()
				}).WithPlayGroups()
			}).WithSpouse(func(q *ent.PetQuery) {
				q.WithBadge().WithProtege(func(q *ent.PetQuery) {
					q.WithBadge().WithToys().WithParent(func(q *ent.PetQuery) {
						q.WithBadge().WithToys().WithParent(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						}).WithPlayGroups()
					}).WithPlayGroups()
				}).WithToys().WithParent(func(q *ent.PetQuery) {
					q.WithBadge().WithProtege(func(q *ent.PetQuery) {
						q.WithBadge().WithToys().WithParent(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						}).WithPlayGroups()
					}).WithToys().WithParent(func(q *ent.PetQuery) {
						q.WithBadge().WithProtege(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						}).WithToys().WithPlayGroups()
					}).WithPlayGroups()
				}).WithPlayGroups()
			}).WithToys().WithParent(func(q *ent.PetQuery) {
				q.WithBadge().WithProtege(func(q *ent.PetQuery) {
					q.WithBadge().WithSpouse(func(q *ent.PetQuery) {
						q.WithBadge().WithToys().WithParent(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						}).WithPlayGroups()
					}).WithToys().WithParent(func(q *ent.PetQuery) {
						q.WithBadge().WithSpouse(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						}).WithToys().WithPlayGroups()
					}).WithPlayGroups()
				}).WithSpouse(func(q *ent.PetQuery) {
					q.WithBadge().WithProtege(func(q *ent.PetQuery) {
						q.WithBadge().WithToys().WithParent(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						}).WithPlayGroups()
					}).WithToys().WithParent(func(q *ent.PetQuery) {
						q.WithBadge().WithProtege(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						}).WithToys().WithPlayGroups()
					}).WithPlayGroups()
				}).WithToys().WithParent(func(q *ent.PetQuery) {
					q.WithBadge().WithProtege(func(q *ent.PetQuery) {
						q.WithBadge().WithSpouse(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						}).WithToys().WithPlayGroups()
					}).WithSpouse(func(q *ent.PetQuery) {
						q.WithBadge().WithProtege(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						}).WithToys().WithPlayGroups()
					}).WithToys().WithPlayGroups()
				}).WithPlayGroups()
			}).WithPlayGroups()
		})
	})

	e, err := q.Only(r.Context())
	if err != nil {
		switch {
		case ent.IsNotFound(err):
			msg := stripEntError(err)
			l.Info(msg, zap.Error(err), zap.Int("id", id))
			c.Status(404).SendString(msg)
		case ent.IsNotSingular(err):
			msg := stripEntError(err)
			l.Error(msg, zap.Error(err), zap.Int("id", id))
			c.Status(400).SendString(msg)
		default:
			l.Error("could-not-read-toy", zap.Error(err), zap.Int("id", id))
			c.Status(fiber.StatusInternalServerError).SendString("Serve Error")
		}
		return nil
	}
	l.Info("pet rendered", zap.Int("id", e.ID))
	return c.JSON(NewPet340207500View(e))
}

const (
	ToyCreateRoute Routes = 1 << iota
	ToyReadRoute
	ToyUpdateRoute
	ToyDeleteRoute
	ToyListRoute
	ToyOwnerRoute
	ToyRoutes = 1<<iota - 1
)

// ToyHandler handles http crud operations on ent.Toy.
type ToyHandler struct {
	handler

	client *ent.Client
	log    *zap.Logger
}

func NewToyHandler(c *ent.Client, l *zap.Logger) *ToyHandler {
	return &ToyHandler{
		client: c,
		log:    l.With(zap.String("handler", "ToyHandler")),
	}
}

// RegisterHandlers registers the generated handlers on the given chi router.
func (h *ToyHandler) Mount(r fiber.Router, rs Routes) {
	if rs.has(ToyCreateRoute) {
		r.Post("/", h.Create)
	}
	if rs.has(ToyReadRoute) {
		r.Get("/:id", h.Read)
	}
	if rs.has(ToyUpdateRoute) {
		r.Patch("/:id", h.Update)
	}
	if rs.has(ToyDeleteRoute) {
		r.Delete("/:id", h.Delete)
	}
	if rs.has(ToyListRoute) {
		r.Get("/", h.List)
	}
	if rs.has(ToyOwnerRoute) {
		r.Get("/:id/owner", h.Owner)
	}
}
