// Code generated by entc, DO NOT EDIT.

package http

import (
	"net/http"
	"strconv"

	"github.com/gofiber/fiber/v2"
	"github.com/masseelch/elk/internal/integration/pets/ent"
	badge "github.com/masseelch/elk/internal/integration/pets/ent/badge"
	pet "github.com/masseelch/elk/internal/integration/pets/ent/pet"
	playgroup "github.com/masseelch/elk/internal/integration/pets/ent/playgroup"
	toy "github.com/masseelch/elk/internal/integration/pets/ent/toy"
	"github.com/valyala/fasthttp/fasthttpadaptor"
	"go.uber.org/zap"
)

// @Summary Update a Badge
// @Description Update a Badge
// @ID Update a Badge
// @Tags [Badge]
// @Accept  json
// @Produce  json
// @Param id path int true "Badge ID"
// @Success 200 {object} ent.Badge
// @Failure 400 {object} main.HTTPError
// @Failure 404 {object} main.HTTPError
// @Failure 500 {object} main.HTTPError
// @Router /badge/{id} [patch]
// Update updates a given ent.Badge and saves the changes to the database.
func (h BadgeHandler) Update(c *fiber.Ctx) error {
	l := h.log.With(zap.String("method", "Update"))
	// ID is URL parameter.
	id, err := strconv.Atoi(c.Params("id"))
	if err != nil {
		l.Error("error getting id from url parameter", zap.String("id", c.Params("id")), zap.Error(err))
		return c.Status(400).SendString("id must be an integer greater zero")
	}
	// Get the post data.
	d := new(BadgeUpdateRequest)
	var r http.Request
	fasthttpadaptor.ConvertRequest(c.Context(), &r, true)

	if err := c.BodyParser(d); err != nil {
		l.Error("error decoding json", zap.Error(err))
		return c.Status(400).SendString("invalid json string")
	}
	// Save the data.
	b := h.client.Badge.UpdateOneID(id)
	if d.Color != nil {
		b.SetColor(*d.Color)
	}
	if d.Material != nil {
		b.SetMaterial(*d.Material)
	}
	if d.Wearer != nil {
		b.SetWearerID(*d.Wearer)

	}
	// Store in database.
	e, err := b.Save(r.Context())
	if err != nil {
		switch {
		case ent.IsNotFound(err):
			msg := stripEntError(err)
			l.Info(msg, zap.Error(err), zap.Int("id", id))
			c.Status(404).SendString(msg)
		case ent.IsNotSingular(err):
			msg := stripEntError(err)
			l.Error(msg, zap.Error(err), zap.Int("id", id))
			c.Status(400).SendString(msg)
		default:
			l.Error("could-not-update-badge", zap.Error(err), zap.Int("id", id))
			c.Status(fiber.StatusInternalServerError).SendString("Serve Error")
		}
		return nil
	}
	// Reload entry.
	q := h.client.Badge.Query().Where(badge.ID(e.ID))
	e, err = q.Only(r.Context())
	if err != nil {
		switch {
		case ent.IsNotFound(err):
			msg := stripEntError(err)
			l.Info(msg, zap.Error(err), zap.Int("id", id))
			c.Status(404).SendString(msg)
		case ent.IsNotSingular(err):
			msg := stripEntError(err)
			l.Error(msg, zap.Error(err), zap.Int("id", id))
			c.Status(400).SendString(msg)
		default:
			l.Error("could-not-read-badge", zap.Error(err), zap.Int("id", id))
			c.Status(fiber.StatusInternalServerError).SendString("Serve Error")
		}
		return nil
	}
	l.Info("badge rendered", zap.Int("id", e.ID))
	return c.JSON(NewBadge2492344257View(e))
}

// @Summary Update a Pet
// @Description Update a Pet
// @ID Update a Pet
// @Tags [Pet]
// @Accept  json
// @Produce  json
// @Param id path int true "Pet ID"
// @Success 200 {object} ent.Pet
// @Failure 400 {object} main.HTTPError
// @Failure 404 {object} main.HTTPError
// @Failure 500 {object} main.HTTPError
// @Router /pet/{id} [patch]
// Update updates a given ent.Pet and saves the changes to the database.
func (h PetHandler) Update(c *fiber.Ctx) error {
	l := h.log.With(zap.String("method", "Update"))
	// ID is URL parameter.
	id, err := strconv.Atoi(c.Params("id"))
	if err != nil {
		l.Error("error getting id from url parameter", zap.String("id", c.Params("id")), zap.Error(err))
		return c.Status(400).SendString("id must be an integer greater zero")
	}
	// Get the post data.
	d := new(PetUpdateRequest)
	var r http.Request
	fasthttpadaptor.ConvertRequest(c.Context(), &r, true)

	if err := c.BodyParser(d); err != nil {
		l.Error("error decoding json", zap.Error(err))
		return c.Status(400).SendString("invalid json string")
	}
	// Validate the data.
	errs := make(map[string]string)
	if d.Height == nil {
		errs["height"] = `missing required field: "height"`
	} else if err := pet.HeightValidator(*d.Height); err != nil {
		errs["height"] = err.Error()
	}
	if d.Weight != nil {
		if err := pet.WeightValidator(*d.Weight); err != nil {
			errs["weight"] = err.Error()
		}
	}
	if d.Castrated == nil {
		errs["castrated"] = `missing required field: "castrated"`
	}
	if d.Name == nil {
		errs["name"] = `missing required field: "name"`
	}
	if d.Sex == nil {
		errs["sex"] = `missing required field: "sex"`
	} else if err := pet.SexValidator(*d.Sex); err != nil {
		errs["sex"] = err.Error()
	}
	if d.Chip == nil {
		errs["chip"] = `missing required field: "chip"`
	}
	if d.Badge == nil {
		errs["badge"] = `missing required edge "badge"`
	}
	if len(errs) > 0 {
		l.Info("validation failed", zapFields(errs)...)
		return c.Status(400).JSON(errs)

	}
	// Save the data.
	b := h.client.Pet.UpdateOneID(id)
	if d.Height != nil {
		b.SetHeight(*d.Height)
	}
	if d.Weight != nil {
		b.SetWeight(*d.Weight)
	}
	if d.Castrated != nil {
		b.SetCastrated(*d.Castrated)
	}
	if d.Name != nil {
		b.SetName(*d.Name)
	}
	if d.Birthday != nil {
		b.SetBirthday(*d.Birthday)
	}
	if d.Nicknames != nil {
		b.SetNicknames(*d.Nicknames)
	}
	if d.Sex != nil {
		b.SetSex(*d.Sex)
	}
	if d.Chip != nil {
		b.SetChip(*d.Chip)
	}
	if d.Badge != nil {
		b.SetBadgeID(*d.Badge)

	}
	if d.Protege != nil {
		b.SetProtegeID(*d.Protege)

	}
	if d.Mentor != nil {
		b.SetMentorID(*d.Mentor)

	}
	if d.Spouse != nil {
		b.SetSpouseID(*d.Spouse)

	}
	if d.Toys != nil {
		b.ClearToys().AddToyIDs(d.Toys...)
	}
	if d.Parent != nil {
		b.SetParentID(*d.Parent)

	}
	if d.Children != nil {
		b.ClearChildren().AddChildIDs(d.Children...)
	}
	if d.PlayGroups != nil {
		b.ClearPlayGroups().AddPlayGroupIDs(d.PlayGroups...)
	}
	if d.Friends != nil {
		b.ClearFriends().AddFriendIDs(d.Friends...)
	}
	// Store in database.
	e, err := b.Save(r.Context())
	if err != nil {
		switch {
		case ent.IsNotFound(err):
			msg := stripEntError(err)
			l.Info(msg, zap.Error(err), zap.Int("id", id))
			c.Status(404).SendString(msg)
		case ent.IsNotSingular(err):
			msg := stripEntError(err)
			l.Error(msg, zap.Error(err), zap.Int("id", id))
			c.Status(400).SendString(msg)
		default:
			l.Error("could-not-update-pet", zap.Error(err), zap.Int("id", id))
			c.Status(fiber.StatusInternalServerError).SendString("Serve Error")
		}
		return nil
	}
	// Reload entry.
	q := h.client.Pet.Query().Where(pet.ID(e.ID))
	// Eager load edges that are required on update operation.
	q.WithBadge().WithProtege(func(q *ent.PetQuery) {
		q.WithBadge().WithSpouse(func(q *ent.PetQuery) {
			q.WithBadge().WithToys().WithParent(func(q *ent.PetQuery) {
				q.WithBadge().WithToys().WithParent(func(q *ent.PetQuery) {
					q.WithBadge().WithToys().WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
						q.WithBadge().WithToys().WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						})
					})
				}).WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
					q.WithBadge().WithToys().WithParent(func(q *ent.PetQuery) {
						q.WithBadge().WithToys().WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						})
					}).WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
						q.WithBadge().WithToys().WithParent(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						}).WithPlayGroups()
					})
				})
			}).WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
				q.WithBadge().WithToys().WithParent(func(q *ent.PetQuery) {
					q.WithBadge().WithToys().WithParent(func(q *ent.PetQuery) {
						q.WithBadge().WithToys().WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						})
					}).WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
						q.WithBadge().WithToys().WithParent(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						}).WithPlayGroups()
					})
				}).WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
					q.WithBadge().WithToys().WithParent(func(q *ent.PetQuery) {
						q.WithBadge().WithToys().WithParent(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						}).WithPlayGroups()
					}).WithPlayGroups()
				})
			})
		}).WithToys().WithParent(func(q *ent.PetQuery) {
			q.WithBadge().WithSpouse(func(q *ent.PetQuery) {
				q.WithBadge().WithToys().WithParent(func(q *ent.PetQuery) {
					q.WithBadge().WithToys().WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
						q.WithBadge().WithToys().WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						})
					})
				}).WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
					q.WithBadge().WithToys().WithParent(func(q *ent.PetQuery) {
						q.WithBadge().WithToys().WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						})
					}).WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
						q.WithBadge().WithToys().WithParent(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						}).WithPlayGroups()
					})
				})
			}).WithToys().WithParent(func(q *ent.PetQuery) {
				q.WithBadge().WithSpouse(func(q *ent.PetQuery) {
					q.WithBadge().WithToys().WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
						q.WithBadge().WithToys().WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						})
					})
				}).WithToys().WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
					q.WithBadge().WithSpouse(func(q *ent.PetQuery) {
						q.WithBadge().WithToys().WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						})
					}).WithToys().WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
						q.WithBadge().WithSpouse(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						}).WithToys().WithPlayGroups()
					})
				})
			}).WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
				q.WithBadge().WithSpouse(func(q *ent.PetQuery) {
					q.WithBadge().WithToys().WithParent(func(q *ent.PetQuery) {
						q.WithBadge().WithToys().WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						})
					}).WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
						q.WithBadge().WithToys().WithParent(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						}).WithPlayGroups()
					})
				}).WithToys().WithParent(func(q *ent.PetQuery) {
					q.WithBadge().WithSpouse(func(q *ent.PetQuery) {
						q.WithBadge().WithToys().WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						})
					}).WithToys().WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
						q.WithBadge().WithSpouse(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						}).WithToys().WithPlayGroups()
					})
				}).WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
					q.WithBadge().WithSpouse(func(q *ent.PetQuery) {
						q.WithBadge().WithToys().WithParent(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						}).WithPlayGroups()
					}).WithToys().WithParent(func(q *ent.PetQuery) {
						q.WithBadge().WithSpouse(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						}).WithToys().WithPlayGroups()
					}).WithPlayGroups()
				})
			})
		}).WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
			q.WithBadge().WithSpouse(func(q *ent.PetQuery) {
				q.WithBadge().WithToys().WithParent(func(q *ent.PetQuery) {
					q.WithBadge().WithToys().WithParent(func(q *ent.PetQuery) {
						q.WithBadge().WithToys().WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						})
					}).WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
						q.WithBadge().WithToys().WithParent(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						}).WithPlayGroups()
					})
				}).WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
					q.WithBadge().WithToys().WithParent(func(q *ent.PetQuery) {
						q.WithBadge().WithToys().WithParent(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						}).WithPlayGroups()
					}).WithPlayGroups()
				})
			}).WithToys().WithParent(func(q *ent.PetQuery) {
				q.WithBadge().WithSpouse(func(q *ent.PetQuery) {
					q.WithBadge().WithToys().WithParent(func(q *ent.PetQuery) {
						q.WithBadge().WithToys().WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						})
					}).WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
						q.WithBadge().WithToys().WithParent(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						}).WithPlayGroups()
					})
				}).WithToys().WithParent(func(q *ent.PetQuery) {
					q.WithBadge().WithSpouse(func(q *ent.PetQuery) {
						q.WithBadge().WithToys().WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						})
					}).WithToys().WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
						q.WithBadge().WithSpouse(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						}).WithToys().WithPlayGroups()
					})
				}).WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
					q.WithBadge().WithSpouse(func(q *ent.PetQuery) {
						q.WithBadge().WithToys().WithParent(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						}).WithPlayGroups()
					}).WithToys().WithParent(func(q *ent.PetQuery) {
						q.WithBadge().WithSpouse(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						}).WithToys().WithPlayGroups()
					}).WithPlayGroups()
				})
			}).WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
				q.WithBadge().WithSpouse(func(q *ent.PetQuery) {
					q.WithBadge().WithToys().WithParent(func(q *ent.PetQuery) {
						q.WithBadge().WithToys().WithParent(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						}).WithPlayGroups()
					}).WithPlayGroups()
				}).WithToys().WithParent(func(q *ent.PetQuery) {
					q.WithBadge().WithSpouse(func(q *ent.PetQuery) {
						q.WithBadge().WithToys().WithParent(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						}).WithPlayGroups()
					}).WithToys().WithParent(func(q *ent.PetQuery) {
						q.WithBadge().WithSpouse(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						}).WithToys().WithPlayGroups()
					}).WithPlayGroups()
				}).WithPlayGroups()
			})
		})
	}).WithSpouse(func(q *ent.PetQuery) {
		q.WithBadge().WithProtege(func(q *ent.PetQuery) {
			q.WithBadge().WithToys().WithParent(func(q *ent.PetQuery) {
				q.WithBadge().WithToys().WithParent(func(q *ent.PetQuery) {
					q.WithBadge().WithToys().WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
						q.WithBadge().WithToys().WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						})
					})
				}).WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
					q.WithBadge().WithToys().WithParent(func(q *ent.PetQuery) {
						q.WithBadge().WithToys().WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						})
					}).WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
						q.WithBadge().WithToys().WithParent(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						}).WithPlayGroups()
					})
				})
			}).WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
				q.WithBadge().WithToys().WithParent(func(q *ent.PetQuery) {
					q.WithBadge().WithToys().WithParent(func(q *ent.PetQuery) {
						q.WithBadge().WithToys().WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						})
					}).WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
						q.WithBadge().WithToys().WithParent(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						}).WithPlayGroups()
					})
				}).WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
					q.WithBadge().WithToys().WithParent(func(q *ent.PetQuery) {
						q.WithBadge().WithToys().WithParent(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						}).WithPlayGroups()
					}).WithPlayGroups()
				})
			})
		}).WithToys().WithParent(func(q *ent.PetQuery) {
			q.WithBadge().WithProtege(func(q *ent.PetQuery) {
				q.WithBadge().WithToys().WithParent(func(q *ent.PetQuery) {
					q.WithBadge().WithToys().WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
						q.WithBadge().WithToys().WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						})
					})
				}).WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
					q.WithBadge().WithToys().WithParent(func(q *ent.PetQuery) {
						q.WithBadge().WithToys().WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						})
					}).WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
						q.WithBadge().WithToys().WithParent(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						}).WithPlayGroups()
					})
				})
			}).WithToys().WithParent(func(q *ent.PetQuery) {
				q.WithBadge().WithProtege(func(q *ent.PetQuery) {
					q.WithBadge().WithToys().WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
						q.WithBadge().WithToys().WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						})
					})
				}).WithToys().WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
					q.WithBadge().WithProtege(func(q *ent.PetQuery) {
						q.WithBadge().WithToys().WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						})
					}).WithToys().WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
						q.WithBadge().WithProtege(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						}).WithToys().WithPlayGroups()
					})
				})
			}).WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
				q.WithBadge().WithProtege(func(q *ent.PetQuery) {
					q.WithBadge().WithToys().WithParent(func(q *ent.PetQuery) {
						q.WithBadge().WithToys().WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						})
					}).WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
						q.WithBadge().WithToys().WithParent(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						}).WithPlayGroups()
					})
				}).WithToys().WithParent(func(q *ent.PetQuery) {
					q.WithBadge().WithProtege(func(q *ent.PetQuery) {
						q.WithBadge().WithToys().WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						})
					}).WithToys().WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
						q.WithBadge().WithProtege(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						}).WithToys().WithPlayGroups()
					})
				}).WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
					q.WithBadge().WithProtege(func(q *ent.PetQuery) {
						q.WithBadge().WithToys().WithParent(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						}).WithPlayGroups()
					}).WithToys().WithParent(func(q *ent.PetQuery) {
						q.WithBadge().WithProtege(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						}).WithToys().WithPlayGroups()
					}).WithPlayGroups()
				})
			})
		}).WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
			q.WithBadge().WithProtege(func(q *ent.PetQuery) {
				q.WithBadge().WithToys().WithParent(func(q *ent.PetQuery) {
					q.WithBadge().WithToys().WithParent(func(q *ent.PetQuery) {
						q.WithBadge().WithToys().WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						})
					}).WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
						q.WithBadge().WithToys().WithParent(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						}).WithPlayGroups()
					})
				}).WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
					q.WithBadge().WithToys().WithParent(func(q *ent.PetQuery) {
						q.WithBadge().WithToys().WithParent(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						}).WithPlayGroups()
					}).WithPlayGroups()
				})
			}).WithToys().WithParent(func(q *ent.PetQuery) {
				q.WithBadge().WithProtege(func(q *ent.PetQuery) {
					q.WithBadge().WithToys().WithParent(func(q *ent.PetQuery) {
						q.WithBadge().WithToys().WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						})
					}).WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
						q.WithBadge().WithToys().WithParent(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						}).WithPlayGroups()
					})
				}).WithToys().WithParent(func(q *ent.PetQuery) {
					q.WithBadge().WithProtege(func(q *ent.PetQuery) {
						q.WithBadge().WithToys().WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						})
					}).WithToys().WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
						q.WithBadge().WithProtege(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						}).WithToys().WithPlayGroups()
					})
				}).WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
					q.WithBadge().WithProtege(func(q *ent.PetQuery) {
						q.WithBadge().WithToys().WithParent(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						}).WithPlayGroups()
					}).WithToys().WithParent(func(q *ent.PetQuery) {
						q.WithBadge().WithProtege(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						}).WithToys().WithPlayGroups()
					}).WithPlayGroups()
				})
			}).WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
				q.WithBadge().WithProtege(func(q *ent.PetQuery) {
					q.WithBadge().WithToys().WithParent(func(q *ent.PetQuery) {
						q.WithBadge().WithToys().WithParent(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						}).WithPlayGroups()
					}).WithPlayGroups()
				}).WithToys().WithParent(func(q *ent.PetQuery) {
					q.WithBadge().WithProtege(func(q *ent.PetQuery) {
						q.WithBadge().WithToys().WithParent(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						}).WithPlayGroups()
					}).WithToys().WithParent(func(q *ent.PetQuery) {
						q.WithBadge().WithProtege(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						}).WithToys().WithPlayGroups()
					}).WithPlayGroups()
				}).WithPlayGroups()
			})
		})
	}).WithToys().WithParent(func(q *ent.PetQuery) {
		q.WithBadge().WithProtege(func(q *ent.PetQuery) {
			q.WithBadge().WithSpouse(func(q *ent.PetQuery) {
				q.WithBadge().WithToys().WithParent(func(q *ent.PetQuery) {
					q.WithBadge().WithToys().WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
						q.WithBadge().WithToys().WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						})
					})
				}).WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
					q.WithBadge().WithToys().WithParent(func(q *ent.PetQuery) {
						q.WithBadge().WithToys().WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						})
					}).WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
						q.WithBadge().WithToys().WithParent(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						}).WithPlayGroups()
					})
				})
			}).WithToys().WithParent(func(q *ent.PetQuery) {
				q.WithBadge().WithSpouse(func(q *ent.PetQuery) {
					q.WithBadge().WithToys().WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
						q.WithBadge().WithToys().WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						})
					})
				}).WithToys().WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
					q.WithBadge().WithSpouse(func(q *ent.PetQuery) {
						q.WithBadge().WithToys().WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						})
					}).WithToys().WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
						q.WithBadge().WithSpouse(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						}).WithToys().WithPlayGroups()
					})
				})
			}).WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
				q.WithBadge().WithSpouse(func(q *ent.PetQuery) {
					q.WithBadge().WithToys().WithParent(func(q *ent.PetQuery) {
						q.WithBadge().WithToys().WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						})
					}).WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
						q.WithBadge().WithToys().WithParent(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						}).WithPlayGroups()
					})
				}).WithToys().WithParent(func(q *ent.PetQuery) {
					q.WithBadge().WithSpouse(func(q *ent.PetQuery) {
						q.WithBadge().WithToys().WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						})
					}).WithToys().WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
						q.WithBadge().WithSpouse(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						}).WithToys().WithPlayGroups()
					})
				}).WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
					q.WithBadge().WithSpouse(func(q *ent.PetQuery) {
						q.WithBadge().WithToys().WithParent(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						}).WithPlayGroups()
					}).WithToys().WithParent(func(q *ent.PetQuery) {
						q.WithBadge().WithSpouse(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						}).WithToys().WithPlayGroups()
					}).WithPlayGroups()
				})
			})
		}).WithSpouse(func(q *ent.PetQuery) {
			q.WithBadge().WithProtege(func(q *ent.PetQuery) {
				q.WithBadge().WithToys().WithParent(func(q *ent.PetQuery) {
					q.WithBadge().WithToys().WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
						q.WithBadge().WithToys().WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						})
					})
				}).WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
					q.WithBadge().WithToys().WithParent(func(q *ent.PetQuery) {
						q.WithBadge().WithToys().WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						})
					}).WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
						q.WithBadge().WithToys().WithParent(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						}).WithPlayGroups()
					})
				})
			}).WithToys().WithParent(func(q *ent.PetQuery) {
				q.WithBadge().WithProtege(func(q *ent.PetQuery) {
					q.WithBadge().WithToys().WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
						q.WithBadge().WithToys().WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						})
					})
				}).WithToys().WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
					q.WithBadge().WithProtege(func(q *ent.PetQuery) {
						q.WithBadge().WithToys().WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						})
					}).WithToys().WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
						q.WithBadge().WithProtege(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						}).WithToys().WithPlayGroups()
					})
				})
			}).WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
				q.WithBadge().WithProtege(func(q *ent.PetQuery) {
					q.WithBadge().WithToys().WithParent(func(q *ent.PetQuery) {
						q.WithBadge().WithToys().WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						})
					}).WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
						q.WithBadge().WithToys().WithParent(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						}).WithPlayGroups()
					})
				}).WithToys().WithParent(func(q *ent.PetQuery) {
					q.WithBadge().WithProtege(func(q *ent.PetQuery) {
						q.WithBadge().WithToys().WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						})
					}).WithToys().WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
						q.WithBadge().WithProtege(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						}).WithToys().WithPlayGroups()
					})
				}).WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
					q.WithBadge().WithProtege(func(q *ent.PetQuery) {
						q.WithBadge().WithToys().WithParent(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						}).WithPlayGroups()
					}).WithToys().WithParent(func(q *ent.PetQuery) {
						q.WithBadge().WithProtege(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						}).WithToys().WithPlayGroups()
					}).WithPlayGroups()
				})
			})
		}).WithToys().WithParent(func(q *ent.PetQuery) {
			q.WithBadge().WithProtege(func(q *ent.PetQuery) {
				q.WithBadge().WithSpouse(func(q *ent.PetQuery) {
					q.WithBadge().WithToys().WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
						q.WithBadge().WithToys().WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						})
					})
				}).WithToys().WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
					q.WithBadge().WithSpouse(func(q *ent.PetQuery) {
						q.WithBadge().WithToys().WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						})
					}).WithToys().WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
						q.WithBadge().WithSpouse(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						}).WithToys().WithPlayGroups()
					})
				})
			}).WithSpouse(func(q *ent.PetQuery) {
				q.WithBadge().WithProtege(func(q *ent.PetQuery) {
					q.WithBadge().WithToys().WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
						q.WithBadge().WithToys().WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						})
					})
				}).WithToys().WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
					q.WithBadge().WithProtege(func(q *ent.PetQuery) {
						q.WithBadge().WithToys().WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						})
					}).WithToys().WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
						q.WithBadge().WithProtege(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						}).WithToys().WithPlayGroups()
					})
				})
			}).WithToys().WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
				q.WithBadge().WithProtege(func(q *ent.PetQuery) {
					q.WithBadge().WithSpouse(func(q *ent.PetQuery) {
						q.WithBadge().WithToys().WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						})
					}).WithToys().WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
						q.WithBadge().WithSpouse(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						}).WithToys().WithPlayGroups()
					})
				}).WithSpouse(func(q *ent.PetQuery) {
					q.WithBadge().WithProtege(func(q *ent.PetQuery) {
						q.WithBadge().WithToys().WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						})
					}).WithToys().WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
						q.WithBadge().WithProtege(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						}).WithToys().WithPlayGroups()
					})
				}).WithToys().WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
					q.WithBadge().WithProtege(func(q *ent.PetQuery) {
						q.WithBadge().WithSpouse(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						}).WithToys().WithPlayGroups()
					}).WithSpouse(func(q *ent.PetQuery) {
						q.WithBadge().WithProtege(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						}).WithToys().WithPlayGroups()
					}).WithToys().WithPlayGroups()
				})
			})
		}).WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
			q.WithBadge().WithProtege(func(q *ent.PetQuery) {
				q.WithBadge().WithSpouse(func(q *ent.PetQuery) {
					q.WithBadge().WithToys().WithParent(func(q *ent.PetQuery) {
						q.WithBadge().WithToys().WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						})
					}).WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
						q.WithBadge().WithToys().WithParent(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						}).WithPlayGroups()
					})
				}).WithToys().WithParent(func(q *ent.PetQuery) {
					q.WithBadge().WithSpouse(func(q *ent.PetQuery) {
						q.WithBadge().WithToys().WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						})
					}).WithToys().WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
						q.WithBadge().WithSpouse(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						}).WithToys().WithPlayGroups()
					})
				}).WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
					q.WithBadge().WithSpouse(func(q *ent.PetQuery) {
						q.WithBadge().WithToys().WithParent(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						}).WithPlayGroups()
					}).WithToys().WithParent(func(q *ent.PetQuery) {
						q.WithBadge().WithSpouse(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						}).WithToys().WithPlayGroups()
					}).WithPlayGroups()
				})
			}).WithSpouse(func(q *ent.PetQuery) {
				q.WithBadge().WithProtege(func(q *ent.PetQuery) {
					q.WithBadge().WithToys().WithParent(func(q *ent.PetQuery) {
						q.WithBadge().WithToys().WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						})
					}).WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
						q.WithBadge().WithToys().WithParent(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						}).WithPlayGroups()
					})
				}).WithToys().WithParent(func(q *ent.PetQuery) {
					q.WithBadge().WithProtege(func(q *ent.PetQuery) {
						q.WithBadge().WithToys().WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						})
					}).WithToys().WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
						q.WithBadge().WithProtege(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						}).WithToys().WithPlayGroups()
					})
				}).WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
					q.WithBadge().WithProtege(func(q *ent.PetQuery) {
						q.WithBadge().WithToys().WithParent(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						}).WithPlayGroups()
					}).WithToys().WithParent(func(q *ent.PetQuery) {
						q.WithBadge().WithProtege(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						}).WithToys().WithPlayGroups()
					}).WithPlayGroups()
				})
			}).WithToys().WithParent(func(q *ent.PetQuery) {
				q.WithBadge().WithProtege(func(q *ent.PetQuery) {
					q.WithBadge().WithSpouse(func(q *ent.PetQuery) {
						q.WithBadge().WithToys().WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						})
					}).WithToys().WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
						q.WithBadge().WithSpouse(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						}).WithToys().WithPlayGroups()
					})
				}).WithSpouse(func(q *ent.PetQuery) {
					q.WithBadge().WithProtege(func(q *ent.PetQuery) {
						q.WithBadge().WithToys().WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						})
					}).WithToys().WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
						q.WithBadge().WithProtege(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						}).WithToys().WithPlayGroups()
					})
				}).WithToys().WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
					q.WithBadge().WithProtege(func(q *ent.PetQuery) {
						q.WithBadge().WithSpouse(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						}).WithToys().WithPlayGroups()
					}).WithSpouse(func(q *ent.PetQuery) {
						q.WithBadge().WithProtege(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						}).WithToys().WithPlayGroups()
					}).WithToys().WithPlayGroups()
				})
			}).WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
				q.WithBadge().WithProtege(func(q *ent.PetQuery) {
					q.WithBadge().WithSpouse(func(q *ent.PetQuery) {
						q.WithBadge().WithToys().WithParent(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						}).WithPlayGroups()
					}).WithToys().WithParent(func(q *ent.PetQuery) {
						q.WithBadge().WithSpouse(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						}).WithToys().WithPlayGroups()
					}).WithPlayGroups()
				}).WithSpouse(func(q *ent.PetQuery) {
					q.WithBadge().WithProtege(func(q *ent.PetQuery) {
						q.WithBadge().WithToys().WithParent(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						}).WithPlayGroups()
					}).WithToys().WithParent(func(q *ent.PetQuery) {
						q.WithBadge().WithProtege(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						}).WithToys().WithPlayGroups()
					}).WithPlayGroups()
				}).WithToys().WithParent(func(q *ent.PetQuery) {
					q.WithBadge().WithProtege(func(q *ent.PetQuery) {
						q.WithBadge().WithSpouse(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						}).WithToys().WithPlayGroups()
					}).WithSpouse(func(q *ent.PetQuery) {
						q.WithBadge().WithProtege(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						}).WithToys().WithPlayGroups()
					}).WithToys().WithPlayGroups()
				}).WithPlayGroups()
			})
		})
	}).WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
		q.WithBadge().WithProtege(func(q *ent.PetQuery) {
			q.WithBadge().WithSpouse(func(q *ent.PetQuery) {
				q.WithBadge().WithToys().WithParent(func(q *ent.PetQuery) {
					q.WithBadge().WithToys().WithParent(func(q *ent.PetQuery) {
						q.WithBadge().WithToys().WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						})
					}).WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
						q.WithBadge().WithToys().WithParent(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						}).WithPlayGroups()
					})
				}).WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
					q.WithBadge().WithToys().WithParent(func(q *ent.PetQuery) {
						q.WithBadge().WithToys().WithParent(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						}).WithPlayGroups()
					}).WithPlayGroups()
				})
			}).WithToys().WithParent(func(q *ent.PetQuery) {
				q.WithBadge().WithSpouse(func(q *ent.PetQuery) {
					q.WithBadge().WithToys().WithParent(func(q *ent.PetQuery) {
						q.WithBadge().WithToys().WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						})
					}).WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
						q.WithBadge().WithToys().WithParent(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						}).WithPlayGroups()
					})
				}).WithToys().WithParent(func(q *ent.PetQuery) {
					q.WithBadge().WithSpouse(func(q *ent.PetQuery) {
						q.WithBadge().WithToys().WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						})
					}).WithToys().WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
						q.WithBadge().WithSpouse(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						}).WithToys().WithPlayGroups()
					})
				}).WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
					q.WithBadge().WithSpouse(func(q *ent.PetQuery) {
						q.WithBadge().WithToys().WithParent(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						}).WithPlayGroups()
					}).WithToys().WithParent(func(q *ent.PetQuery) {
						q.WithBadge().WithSpouse(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						}).WithToys().WithPlayGroups()
					}).WithPlayGroups()
				})
			}).WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
				q.WithBadge().WithSpouse(func(q *ent.PetQuery) {
					q.WithBadge().WithToys().WithParent(func(q *ent.PetQuery) {
						q.WithBadge().WithToys().WithParent(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						}).WithPlayGroups()
					}).WithPlayGroups()
				}).WithToys().WithParent(func(q *ent.PetQuery) {
					q.WithBadge().WithSpouse(func(q *ent.PetQuery) {
						q.WithBadge().WithToys().WithParent(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						}).WithPlayGroups()
					}).WithToys().WithParent(func(q *ent.PetQuery) {
						q.WithBadge().WithSpouse(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						}).WithToys().WithPlayGroups()
					}).WithPlayGroups()
				}).WithPlayGroups()
			})
		}).WithSpouse(func(q *ent.PetQuery) {
			q.WithBadge().WithProtege(func(q *ent.PetQuery) {
				q.WithBadge().WithToys().WithParent(func(q *ent.PetQuery) {
					q.WithBadge().WithToys().WithParent(func(q *ent.PetQuery) {
						q.WithBadge().WithToys().WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						})
					}).WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
						q.WithBadge().WithToys().WithParent(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						}).WithPlayGroups()
					})
				}).WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
					q.WithBadge().WithToys().WithParent(func(q *ent.PetQuery) {
						q.WithBadge().WithToys().WithParent(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						}).WithPlayGroups()
					}).WithPlayGroups()
				})
			}).WithToys().WithParent(func(q *ent.PetQuery) {
				q.WithBadge().WithProtege(func(q *ent.PetQuery) {
					q.WithBadge().WithToys().WithParent(func(q *ent.PetQuery) {
						q.WithBadge().WithToys().WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						})
					}).WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
						q.WithBadge().WithToys().WithParent(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						}).WithPlayGroups()
					})
				}).WithToys().WithParent(func(q *ent.PetQuery) {
					q.WithBadge().WithProtege(func(q *ent.PetQuery) {
						q.WithBadge().WithToys().WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						})
					}).WithToys().WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
						q.WithBadge().WithProtege(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						}).WithToys().WithPlayGroups()
					})
				}).WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
					q.WithBadge().WithProtege(func(q *ent.PetQuery) {
						q.WithBadge().WithToys().WithParent(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						}).WithPlayGroups()
					}).WithToys().WithParent(func(q *ent.PetQuery) {
						q.WithBadge().WithProtege(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						}).WithToys().WithPlayGroups()
					}).WithPlayGroups()
				})
			}).WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
				q.WithBadge().WithProtege(func(q *ent.PetQuery) {
					q.WithBadge().WithToys().WithParent(func(q *ent.PetQuery) {
						q.WithBadge().WithToys().WithParent(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						}).WithPlayGroups()
					}).WithPlayGroups()
				}).WithToys().WithParent(func(q *ent.PetQuery) {
					q.WithBadge().WithProtege(func(q *ent.PetQuery) {
						q.WithBadge().WithToys().WithParent(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						}).WithPlayGroups()
					}).WithToys().WithParent(func(q *ent.PetQuery) {
						q.WithBadge().WithProtege(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						}).WithToys().WithPlayGroups()
					}).WithPlayGroups()
				}).WithPlayGroups()
			})
		}).WithToys().WithParent(func(q *ent.PetQuery) {
			q.WithBadge().WithProtege(func(q *ent.PetQuery) {
				q.WithBadge().WithSpouse(func(q *ent.PetQuery) {
					q.WithBadge().WithToys().WithParent(func(q *ent.PetQuery) {
						q.WithBadge().WithToys().WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						})
					}).WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
						q.WithBadge().WithToys().WithParent(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						}).WithPlayGroups()
					})
				}).WithToys().WithParent(func(q *ent.PetQuery) {
					q.WithBadge().WithSpouse(func(q *ent.PetQuery) {
						q.WithBadge().WithToys().WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						})
					}).WithToys().WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
						q.WithBadge().WithSpouse(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						}).WithToys().WithPlayGroups()
					})
				}).WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
					q.WithBadge().WithSpouse(func(q *ent.PetQuery) {
						q.WithBadge().WithToys().WithParent(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						}).WithPlayGroups()
					}).WithToys().WithParent(func(q *ent.PetQuery) {
						q.WithBadge().WithSpouse(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						}).WithToys().WithPlayGroups()
					}).WithPlayGroups()
				})
			}).WithSpouse(func(q *ent.PetQuery) {
				q.WithBadge().WithProtege(func(q *ent.PetQuery) {
					q.WithBadge().WithToys().WithParent(func(q *ent.PetQuery) {
						q.WithBadge().WithToys().WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						})
					}).WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
						q.WithBadge().WithToys().WithParent(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						}).WithPlayGroups()
					})
				}).WithToys().WithParent(func(q *ent.PetQuery) {
					q.WithBadge().WithProtege(func(q *ent.PetQuery) {
						q.WithBadge().WithToys().WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						})
					}).WithToys().WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
						q.WithBadge().WithProtege(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						}).WithToys().WithPlayGroups()
					})
				}).WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
					q.WithBadge().WithProtege(func(q *ent.PetQuery) {
						q.WithBadge().WithToys().WithParent(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						}).WithPlayGroups()
					}).WithToys().WithParent(func(q *ent.PetQuery) {
						q.WithBadge().WithProtege(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						}).WithToys().WithPlayGroups()
					}).WithPlayGroups()
				})
			}).WithToys().WithParent(func(q *ent.PetQuery) {
				q.WithBadge().WithProtege(func(q *ent.PetQuery) {
					q.WithBadge().WithSpouse(func(q *ent.PetQuery) {
						q.WithBadge().WithToys().WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						})
					}).WithToys().WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
						q.WithBadge().WithSpouse(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						}).WithToys().WithPlayGroups()
					})
				}).WithSpouse(func(q *ent.PetQuery) {
					q.WithBadge().WithProtege(func(q *ent.PetQuery) {
						q.WithBadge().WithToys().WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						})
					}).WithToys().WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
						q.WithBadge().WithProtege(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						}).WithToys().WithPlayGroups()
					})
				}).WithToys().WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
					q.WithBadge().WithProtege(func(q *ent.PetQuery) {
						q.WithBadge().WithSpouse(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						}).WithToys().WithPlayGroups()
					}).WithSpouse(func(q *ent.PetQuery) {
						q.WithBadge().WithProtege(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						}).WithToys().WithPlayGroups()
					}).WithToys().WithPlayGroups()
				})
			}).WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
				q.WithBadge().WithProtege(func(q *ent.PetQuery) {
					q.WithBadge().WithSpouse(func(q *ent.PetQuery) {
						q.WithBadge().WithToys().WithParent(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						}).WithPlayGroups()
					}).WithToys().WithParent(func(q *ent.PetQuery) {
						q.WithBadge().WithSpouse(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						}).WithToys().WithPlayGroups()
					}).WithPlayGroups()
				}).WithSpouse(func(q *ent.PetQuery) {
					q.WithBadge().WithProtege(func(q *ent.PetQuery) {
						q.WithBadge().WithToys().WithParent(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						}).WithPlayGroups()
					}).WithToys().WithParent(func(q *ent.PetQuery) {
						q.WithBadge().WithProtege(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						}).WithToys().WithPlayGroups()
					}).WithPlayGroups()
				}).WithToys().WithParent(func(q *ent.PetQuery) {
					q.WithBadge().WithProtege(func(q *ent.PetQuery) {
						q.WithBadge().WithSpouse(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						}).WithToys().WithPlayGroups()
					}).WithSpouse(func(q *ent.PetQuery) {
						q.WithBadge().WithProtege(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						}).WithToys().WithPlayGroups()
					}).WithToys().WithPlayGroups()
				}).WithPlayGroups()
			})
		}).WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
			q.WithBadge().WithProtege(func(q *ent.PetQuery) {
				q.WithBadge().WithSpouse(func(q *ent.PetQuery) {
					q.WithBadge().WithToys().WithParent(func(q *ent.PetQuery) {
						q.WithBadge().WithToys().WithParent(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						}).WithPlayGroups()
					}).WithPlayGroups()
				}).WithToys().WithParent(func(q *ent.PetQuery) {
					q.WithBadge().WithSpouse(func(q *ent.PetQuery) {
						q.WithBadge().WithToys().WithParent(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						}).WithPlayGroups()
					}).WithToys().WithParent(func(q *ent.PetQuery) {
						q.WithBadge().WithSpouse(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						}).WithToys().WithPlayGroups()
					}).WithPlayGroups()
				}).WithPlayGroups()
			}).WithSpouse(func(q *ent.PetQuery) {
				q.WithBadge().WithProtege(func(q *ent.PetQuery) {
					q.WithBadge().WithToys().WithParent(func(q *ent.PetQuery) {
						q.WithBadge().WithToys().WithParent(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						}).WithPlayGroups()
					}).WithPlayGroups()
				}).WithToys().WithParent(func(q *ent.PetQuery) {
					q.WithBadge().WithProtege(func(q *ent.PetQuery) {
						q.WithBadge().WithToys().WithParent(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						}).WithPlayGroups()
					}).WithToys().WithParent(func(q *ent.PetQuery) {
						q.WithBadge().WithProtege(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						}).WithToys().WithPlayGroups()
					}).WithPlayGroups()
				}).WithPlayGroups()
			}).WithToys().WithParent(func(q *ent.PetQuery) {
				q.WithBadge().WithProtege(func(q *ent.PetQuery) {
					q.WithBadge().WithSpouse(func(q *ent.PetQuery) {
						q.WithBadge().WithToys().WithParent(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						}).WithPlayGroups()
					}).WithToys().WithParent(func(q *ent.PetQuery) {
						q.WithBadge().WithSpouse(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						}).WithToys().WithPlayGroups()
					}).WithPlayGroups()
				}).WithSpouse(func(q *ent.PetQuery) {
					q.WithBadge().WithProtege(func(q *ent.PetQuery) {
						q.WithBadge().WithToys().WithParent(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						}).WithPlayGroups()
					}).WithToys().WithParent(func(q *ent.PetQuery) {
						q.WithBadge().WithProtege(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						}).WithToys().WithPlayGroups()
					}).WithPlayGroups()
				}).WithToys().WithParent(func(q *ent.PetQuery) {
					q.WithBadge().WithProtege(func(q *ent.PetQuery) {
						q.WithBadge().WithSpouse(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						}).WithToys().WithPlayGroups()
					}).WithSpouse(func(q *ent.PetQuery) {
						q.WithBadge().WithProtege(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						}).WithToys().WithPlayGroups()
					}).WithToys().WithPlayGroups()
				}).WithPlayGroups()
			}).WithPlayGroups()
		})
	})
	e, err = q.Only(r.Context())
	if err != nil {
		switch {
		case ent.IsNotFound(err):
			msg := stripEntError(err)
			l.Info(msg, zap.Error(err), zap.Int("id", id))
			c.Status(404).SendString(msg)
		case ent.IsNotSingular(err):
			msg := stripEntError(err)
			l.Error(msg, zap.Error(err), zap.Int("id", id))
			c.Status(400).SendString(msg)
		default:
			l.Error("could-not-read-pet", zap.Error(err), zap.Int("id", id))
			c.Status(fiber.StatusInternalServerError).SendString("Serve Error")
		}
		return nil
	}
	l.Info("pet rendered", zap.Int("id", e.ID))
	return c.JSON(NewPet340207500View(e))
}

// @Summary Update a PlayGroup
// @Description Update a PlayGroup
// @ID Update a PlayGroup
// @Tags [PlayGroup]
// @Accept  json
// @Produce  json
// @Param id path int true "PlayGroup ID"
// @Success 200 {object} ent.PlayGroup
// @Failure 400 {object} main.HTTPError
// @Failure 404 {object} main.HTTPError
// @Failure 500 {object} main.HTTPError
// @Router /playgroup/{id} [patch]
// Update updates a given ent.PlayGroup and saves the changes to the database.
func (h PlayGroupHandler) Update(c *fiber.Ctx) error {
	l := h.log.With(zap.String("method", "Update"))
	// ID is URL parameter.
	id, err := strconv.Atoi(c.Params("id"))
	if err != nil {
		l.Error("error getting id from url parameter", zap.String("id", c.Params("id")), zap.Error(err))
		return c.Status(400).SendString("id must be an integer greater zero")
	}
	// Get the post data.
	d := new(PlayGroupUpdateRequest)
	var r http.Request
	fasthttpadaptor.ConvertRequest(c.Context(), &r, true)

	if err := c.BodyParser(d); err != nil {
		l.Error("error decoding json", zap.Error(err))
		return c.Status(400).SendString("invalid json string")
	}
	// Save the data.
	b := h.client.PlayGroup.UpdateOneID(id)
	if d.Title != nil {
		b.SetTitle(*d.Title)
	}
	if d.Description != nil {
		b.SetDescription(*d.Description)
	}
	if d.Weekday != nil {
		b.SetWeekday(*d.Weekday)
	}
	if d.Participants != nil {
		b.ClearParticipants().AddParticipantIDs(d.Participants...)
	}
	// Store in database.
	e, err := b.Save(r.Context())
	if err != nil {
		switch {
		case ent.IsNotFound(err):
			msg := stripEntError(err)
			l.Info(msg, zap.Error(err), zap.Int("id", id))
			c.Status(404).SendString(msg)
		case ent.IsNotSingular(err):
			msg := stripEntError(err)
			l.Error(msg, zap.Error(err), zap.Int("id", id))
			c.Status(400).SendString(msg)
		default:
			l.Error("could-not-update-play-group", zap.Error(err), zap.Int("id", id))
			c.Status(fiber.StatusInternalServerError).SendString("Serve Error")
		}
		return nil
	}
	// Reload entry.
	q := h.client.PlayGroup.Query().Where(playgroup.ID(e.ID))
	e, err = q.Only(r.Context())
	if err != nil {
		switch {
		case ent.IsNotFound(err):
			msg := stripEntError(err)
			l.Info(msg, zap.Error(err), zap.Int("id", id))
			c.Status(404).SendString(msg)
		case ent.IsNotSingular(err):
			msg := stripEntError(err)
			l.Error(msg, zap.Error(err), zap.Int("id", id))
			c.Status(400).SendString(msg)
		default:
			l.Error("could-not-read-play-group", zap.Error(err), zap.Int("id", id))
			c.Status(fiber.StatusInternalServerError).SendString("Serve Error")
		}
		return nil
	}
	l.Info("play-group rendered", zap.Int("id", e.ID))
	return c.JSON(NewPlayGroup3432834655View(e))
}

// @Summary Update a Toy
// @Description Update a Toy
// @ID Update a Toy
// @Tags [Toy]
// @Accept  json
// @Produce  json
// @Param id path int true "Toy ID"
// @Success 200 {object} ent.Toy
// @Failure 400 {object} main.HTTPError
// @Failure 404 {object} main.HTTPError
// @Failure 500 {object} main.HTTPError
// @Router /toy/{id} [patch]
// Update updates a given ent.Toy and saves the changes to the database.
func (h ToyHandler) Update(c *fiber.Ctx) error {
	l := h.log.With(zap.String("method", "Update"))
	// ID is URL parameter.
	id, err := strconv.Atoi(c.Params("id"))
	if err != nil {
		l.Error("error getting id from url parameter", zap.String("id", c.Params("id")), zap.Error(err))
		return c.Status(400).SendString("id must be an integer greater zero")
	}
	// Get the post data.
	d := new(ToyUpdateRequest)
	var r http.Request
	fasthttpadaptor.ConvertRequest(c.Context(), &r, true)

	if err := c.BodyParser(d); err != nil {
		l.Error("error decoding json", zap.Error(err))
		return c.Status(400).SendString("invalid json string")
	}
	// Save the data.
	b := h.client.Toy.UpdateOneID(id)
	if d.Color != nil {
		b.SetColor(*d.Color)
	}
	if d.Material != nil {
		b.SetMaterial(*d.Material)
	}
	if d.Title != nil {
		b.SetTitle(*d.Title)
	}
	if d.Owner != nil {
		b.SetOwnerID(*d.Owner)

	}
	// Store in database.
	e, err := b.Save(r.Context())
	if err != nil {
		switch {
		case ent.IsNotFound(err):
			msg := stripEntError(err)
			l.Info(msg, zap.Error(err), zap.Int("id", id))
			c.Status(404).SendString(msg)
		case ent.IsNotSingular(err):
			msg := stripEntError(err)
			l.Error(msg, zap.Error(err), zap.Int("id", id))
			c.Status(400).SendString(msg)
		default:
			l.Error("could-not-update-toy", zap.Error(err), zap.Int("id", id))
			c.Status(fiber.StatusInternalServerError).SendString("Serve Error")
		}
		return nil
	}
	// Reload entry.
	q := h.client.Toy.Query().Where(toy.ID(e.ID))
	e, err = q.Only(r.Context())
	if err != nil {
		switch {
		case ent.IsNotFound(err):
			msg := stripEntError(err)
			l.Info(msg, zap.Error(err), zap.Int("id", id))
			c.Status(404).SendString(msg)
		case ent.IsNotSingular(err):
			msg := stripEntError(err)
			l.Error(msg, zap.Error(err), zap.Int("id", id))
			c.Status(400).SendString(msg)
		default:
			l.Error("could-not-read-toy", zap.Error(err), zap.Int("id", id))
			c.Status(fiber.StatusInternalServerError).SendString("Serve Error")
		}
		return nil
	}
	l.Info("toy rendered", zap.Int("id", e.ID))
	return c.JSON(NewToy36157710View(e))
}
